### PR TITLE
FIX-#9999: test unicode_escape param

### PR DESCRIPTION
**Pull request by anmyachev**
Signed-off-by: Anatoly Myachev <anatoly.myachev@intel.com>

## What do these changes do?

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [ ] passes `flake8 modin`
- [ ] passes `black --check modin`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #? 
- [ ] tests added and passing

### CODE REVIEW

**Comment by dchigarev** [comment]
it seems that tests are passing, however modin can't read cvs with `encoding="unicode_escape"`
```python
if __name__ == "__main__":
    import modin.pandas as pd
    import pandas
    from modin.pandas.test.test_io import (
        create_test_pandas_dataframe,
        TEST_CSV_FILENAME,
        df_equals,
    )

    create_test_pandas_dataframe().to_csv(TEST_CSV_FILENAME, encoding="unicode_escape")

    pd_df = pandas.read_csv(TEST_CSV_FILENAME, encoding="unicode_escape")
    md_df = pd.read_csv(TEST_CSV_FILENAME, encoding="unicode_escape")

    print(df_equals(md_df, pd_df)) # False (no AssertionError)

    assert len(md_df) == len(pd_df) # AssertionError: 0 != 4
```

this happens because of a bug in `df_equals`, I've filled it in an issue #2249

**Comment by anmyachev** [comment]
Blocked by #2249.

**Comment by anmyachev** [comment]
> it seems that tests are passing, however modin can't read cvs with `encoding="unicode_escape"`
> 
> ```python
> if __name__ == "__main__":
>     import modin.pandas as pd
>     import pandas
>     from modin.pandas.test.test_io import (
>         create_test_pandas_dataframe,
>         TEST_CSV_FILENAME,
>         df_equals,
>     )
> 
>     create_test_pandas_dataframe().to_csv(TEST_CSV_FILENAME, encoding="unicode_escape")
> 
>     pd_df = pandas.read_csv(TEST_CSV_FILENAME, encoding="unicode_escape")
>     md_df = pd.read_csv(TEST_CSV_FILENAME, encoding="unicode_escape")
> 
>     print(df_equals(md_df, pd_df)) # False (no AssertionError)
> 
>     assert len(md_df) == len(pd_df) # AssertionError: 0 != 4
> ```
> 
> this happens because of a bug in `df_equals`, I've filled it in an issue #2249

I see

**Comment by anmyachev** [comment]
Still investigating io-part of modin and pandas codebase.

**Comment by anmyachev** [comment]
Closed in favor of #2309.

**Pull request closed without merging**
