### PR TITLE
Automatically determining number of partitions based on cores

### PR DESCRIPTION
**Pull request by devin-petersohn**
## Related issue number
#48 

- [x] passes `git diff upstream/master -u -- "*.py" | flake8 --diff`

### CODE REVIEW

**Comment by kunalgosar** [comment]
We should do some benchmark testing to make sure that this is more efficient in most cases.

**Comment by devin-petersohn** [comment]
The partitioning needs to be reworked so that we aren't splitting DataFrames into tiny partitions anyway, I think it's orthogonal. We need something like this because we shouldn't limit the system to 4-16 partitions/threads. If someone is reading a 15GB file into memory, they should be able to use all of their cores to do so. #48 has some more information about the motivation here.

**Comment by kunalgosar** [comment]
My concern here is that if someone has a 32 core machine, `DEFAULT_NPARTITIONS = 64`, and there would be 64*64 = 4096 blocks in a large enough DataFrame. Any operation on blocks, such as `abs` would deploy 4096 remote tasks; this would be very costly.

We should probably do more testing on different machines, before deciding on a good heuristic for npartitions.

**Comment by pschafhalter** [comment]
I'm also not entirely convinced that performance will scale linearly with number of CPUs. Because some functions map across individual blocks (of which there are O(NM)), you'd end up in situations with more tasks than CPUs, causing slowdown due to overhead.

**Comment by devin-petersohn** [comment]
It depends on the size of the DataFrame. What I am trying to say is setting `DEFAULT_NPARTITIONS` is orthogonal to the use of `DEFAULT_NPARTITIONS`. We should not blindly use `DEFAULT_NPARTITIONS` when we partition the DataFrames.

The minimum size of a partition should be ~5-10MB, but, again, this is orthogonal to the `DEFAULT_NPARTITIONS` question. The overhead of deploying a task becomes small enough compared to the cost of any operation on a partition of that size that it becomes negligible. We should not limit the performance of the system for large files based on our observations for small files.

**Comment by simon-mo** [comment]
We can make the assumption that Ray is a high throughput task execution engine. The number task shouldn't be an issue. 

Another concern is the de-serialization overhead. For that I give you this un-interesting plot:
deserialization-overhead

**Comment by devin-petersohn** [comment]
Here is a plot for how the scalability of `read_csv` and `isna` are affected by `DEFAULT_NPARTITIONS`. y-axis is in seconds. 
partitions_plot

The machines were also in-use by other people at the time, so that may affect things. It is also worth noting that `DEFAULT_NPARTITIONS=8` did not work on this dataset because of the 2GB plasma limit.

**Pull request merged**
