### PR TITLE
Add `cov` implementaion for `Series` and `DataFrame`

### LINKED ISSUE #1247: cov function implementation

### PR DESCRIPTION
**Pull request by YarShev**
Signed-off-by: Yaroslav Igoshev yaroslav.igoshev@intel.com

## What do these changes do?

- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #1247, #1217   
- [x] tests added and passing

### CODE REVIEW

**Comment by devin-petersohn** [comment]
@YarShev `cov` can be rewritten in the front-end. I do not think it needs a `querycompiler` implementation.

We can just rewrite it as `(self - self.mean()) * (other - other.mean()) / min(len(self), len(other))`. You should test this of course it may not be perfectly matching pandas because of floating point precision.

**Comment by YarShev** [comment]
@devin-petersohn , I don't think we can just rewrite it using formula for covariance/[correlation](https://github.com/modin-project/modin/pull/1521) (moreover, `pandas` supports some kinds of correlation). At first, we will have different precision (even though it is small) with `pandas` that it is very bad. At second, we have to keep all checks and errors which are presented in `pandas` and `numpy` (because the `cov`/`cor` calls go through `numpy`). I think we can do `cov`/`cor` for `Series` either using query compiler or `default_to_pandas`. Regarding to `cov`/`cor` for `DataFrame`, I suggest to keep the implementation via `default_to_pandas` call. What do you think?

**Comment by devin-petersohn** [comment]
My goal with these implementations is to scale, and `other.to_pandas().squeeze` does not scale. A couple of thoughts on your points:

* The precision issue is something we can warn the user about. It is not ideal, but some precision difference is likely (especially in Python) when it is distributed vs single threaded. We can warn with a message like `"Covariance floating point precision may slightly differ from pandas."`
* For different types of correlation other than Pearson, we can default to pandas at first, warning the user that only pearson correlation is supported.

These are my thoughts on this.

**Comment by YarShev** [comment]
@devin-petersohn , yes, I see that `other.to_pandas().squeeze` does not scale. I will think on an implementation that will be scaled.
And what do you think about copying behavior related with errors `pandas` and `numpy`? If we have error messages are different from `pandas` and `numpy`, is it ok?

**Comment by devin-petersohn** [comment]
>And what do you think about copying behavior related with checks and errors of pandas and numpy? If we will have error messages are different from pandas and numpy, is it ok?

@YarShev It is a good question, we already give some warnings about defaulting to pandas, I think it will be okay as long as it is not an exception. Warnings are just to inform the user. Do you think it is an issue?

**Comment by YarShev** [comment]
@devin-petersohn , regarding to warning (such as `defaulting to pandas`) I have no concerns. I mean if we implement `cov` and `cor` without `pandas` and `numpy` underlying `pandas` then we will have errors/exceptions are different from ones which are occurred in `pandas` and `numpy` when we call `cov` and `cor` from there. What do you think regarding this?

**Comment by devin-petersohn** [comment]
@YarShev I see what you mean. For these types of cases it should be okay. My concern is scalability and performance more than the precise error that pandas gives. For these cases, we may be able to do some extra error checking at the API layer as well.

**Comment by YarShev** [comment]
@devin-petersohn , ok, I will think on this.

**Comment by YarShev** [comment]
@devin-petersohn , ok, then I will apply the same approach to `Series.cov`.

**Comment by YarShev** [comment]
@devin-petersohn , just a friendly reminder.

**Comment by YarShev** [comment]
CI is red because of codecov.

**Pull request merged**
