### PR TITLE
FEAT-#6502: HDK: Add 'enable_multifrag_execution_result=1' HDK launch parameter

### LINKED ISSUE #6502: FEAT: HDK: Add 'enable_multifrag_execution_result=1' HDK launch parameter
It could significantly improve performance of queries, executed on results from the previous queries.

### PR DESCRIPTION
**Pull request by AndreyPavlenko**
## What do these changes do?

- [x] first commit message and PR title follow format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
  > **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your last commit for the CI job that checks the PR title to pick up the new PR title.
- [x] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] signed commit with `git commit -s` 
- [x] Resolves #6502 
- [ ] tests added and passing
- [ ] module layout described at `docs/development/architecture.rst` is up-to-date

### CODE REVIEW

**Review by anmyachev — APPROVED** [review]
LGTM! However won't that slow down any other cases?

**Comment by AndreyPavlenko** [comment]
> LGTM! However won't that slow down any other cases?

We will see in the benchmark reports. According to my experiments, it gets ~8x-10x boost in some cases.

**Review by Garra1980 — APPROVED** [review]
LGTM, let's merge and see perf impact

**Comment by Garra1980** [comment]
@AndreyPavlenko @anmyachev we need to refresh https://modin.readthedocs.io/en/stable/flow/modin/config.html# I guess

**Pull request merged**
