### PR TITLE
Add implementation of read_fwf

### LINKED ISSUE #752: Request to implement read_fwf
### 🤖 This is a bot message 🤖 

feature_requests@modin.org has been sent an email requesting parallel implementation for `read_fwf`.

Note: Issues are created only once per method.

### PR DESCRIPTION
**Pull request by guor8lei**
## What do these changes do?

Parallelize `read_fwf` with `FWFReader` and `PandasFWFParser`. 

Note: There is a lot of duplicate code between `FWFReader` and `CSVReader` in order to support `read_csv` arguments for `read_fwf`, probably should look into how we can reduce this. 

- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s`
- [x] Resolves #752 
- [x] tests added and passing

### CODE REVIEW

**Comment by guor8lei** [comment]
Hi @devin-petersohn ,

Just added a few tests that test the functionality of `read_fwf` with different arguments. I tried to write tests that have about the same coverage as the `read_csv` tests, but I did leave out compression and encodings because pandas doesn't have a `to_fwf` function to easily create test files, unfortunately.

One argument that I had trouble with in particular is `chunksize`, which is supposed to default to the pandas implementation with `cls.single_worker_read(filepath_or_buffer, **kwargs)` when it's nonzero, but it still seems to error whereas `read_csv` didn't. The error message is about `TextFileReader` object not having index or column attributes, but I don't see how this is different from what `read_csv` did.

I'll take a look at it a little more, but for now, I have that particular testcase skipped.

**Comment by devin-petersohn** [comment]
@guor8lei `chunksize` will return an iterator of dataframes, not just one. That has to be handled in the front end similar to the `read_csv` case:

https://github.com/modin-project/modin/blob/master/modin/pandas/io.py#L129-L134

**Comment by guor8lei** [comment]
Ah I see, thanks! Just fixed `chunksize`.

**Comment by devin-petersohn** [comment]
@guor8lei Does `read_fwf` handle `compression`? The keyword arguments `kwds` are opaque, so it is hard to see from the outside what all is supported.

**Comment by guor8lei** [comment]
@devin-petersohn `compression` is supported. I kept it as part of `kwds` because the argument (along with others) isn't explicitly listed in the [`read_fwf` documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_fwf.html), but I tested it all the compression formats and `read_fwf` worked with them.

**Pull request merged**
