### PR TITLE
Switch to OmniSci from conda-forge

### LINKED ISSUE #3057: Switch to omnisci from conda-forge
Right now we're relying on OmniSci from [intel/label/modin](https://anaconda.org/intel/omniscidbe4py) Anaconda channel while all other packages required for Modin itself are available in `conda-forge`.

Since https://github.com/conda-forge/omniscidb-feedstock/pull/39 was merged OmniSci is now available in [conda-forge](https://anaconda.org/conda-forge/pyomniscidbe).

We should switch to that channel to use community (and OmniSci themselves) supported version.

### PR DESCRIPTION
**Pull request by vnlitvinov**
## What do these changes do?
Switch to OmniSci-published packages.

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #3057
- [x] tests added and passing
- [x] module layout described at `docs/developer/architecture.rst` is up-to-date

### CODE REVIEW

**Comment by vnlitvinov** [comment]
Converting to draft until we're completely ready for the switch.

**Comment by anmyachev** [comment]
So now there is no block. Can you rebase? @vnlitvinov

**Comment by vnlitvinov** [comment]
There's no need, we've decided with @Garra1980 to leave it in draft for the time being.

**Review by gshimansky — APPROVED** [review]

**Comment by Garra1980** [comment]
this can be dropped, I suppose?

**Comment by vnlitvinov** [comment]
This depends. I think we should actually revive it given it's effectively conda-forge version of OmniSci which is shipped as part of Intel AI Kit.

**Comment by Garra1980** [comment]
I meant we can close this as we already switched to Omnisci in c-f

**Comment by vnlitvinov** [comment]
Right, superseded by #3308.

**Pull request closed without merging**
