### PR TITLE
FEAT-#6351: Add a simple heuristic for fragment size when running on a GPU

### LINKED ISSUE #6351: HDK: Add a simple heuristic for fragment size when running on a GPU

### PR DESCRIPTION
**Pull request by kurapov-peter**
## What do these changes do?

Set fragment size to a constant for GPU execution via HDK.

- [x] first commit message and PR title follow format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
  > **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your last commit for the CI job that checks the PR title to pick up the new PR title.
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] signed commit with `git commit -s` 
- [x] Resolves #6351 
- [ ] tests added and passing
- [ ] module layout described at `docs/development/architecture.rst` is up-to-date

### CODE REVIEW

**Review by AndreyPavlenko — APPROVED** [review]

**Comment by AndreyPavlenko** [comment]
Please, fix the test failures.

**Review by AndreyPavlenko — APPROVED** [review]

**Review by Garra1980 — DISMISSED** [review]

**Comment by Garra1980** [comment]
Let’s merge then?

**Comment by anmyachev** [comment]
Looks like a mistake in the issue number.

**Comment by kurapov-peter** [comment]
> Looks like a mistake in the issue number.

What's incorrect about it?

**Comment by anmyachev** [comment]
> > Looks like a mistake in the issue number.
> 
> What's incorrect about it?

#6325 is already closed, is it made on purpose? If not pls open a new one.

**Review by anmyachev — APPROVED** [review]

**Pull request merged**
