### PR TITLE
TEST-#2616: remove DEFAULT_NPARTITIONS values assigning

### LINKED ISSUE #2616: Manual partitions number setting in tests is broken
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 20.04
- **Modin version**: d6637304a24f986b5abb12e2b525bc3af97d6cac
- **Python version**:  3.8.6
- **Code we can use to reproduce**:
```
import os

os.environ["MODIN_ENGINE"] = "ray"

import modin.pandas as pd
pd.DEFAULT_NPARTITIONS = 1

data = [x for x in range(10000)]

df = pd.DataFrame(data)
print(len(df._query_compiler._modin_frame._partitions)) # <available number of cores>
```

### Describe the problem

Occurred after 9a6695d3b36cb6c21e835b10d62f26a474583f15 commit.

### PR DESCRIPTION
**Pull request by amyskov**
Signed-off-by: Alexander Myskov <alexander.myskov@intel.com>

## What do these changes do?

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/CONTRIBUTING.html)
- [ ] passes `flake8 modin`
- [ ] passes `black --check modin`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #2616 
- [ ] tests passing

### CODE REVIEW

**Comment by devin-petersohn** [comment]
I will fix this issue. I think we should set up a config to be able to change it at runtime as well instead of setting once.

**Comment by amyskov** [comment]
> I will fix this issue. I think we should set up a config to be able to change it at runtime as well instead of setting once.

Great, config is better way.

**Comment by devin-petersohn** [comment]
Fix is in #2622

**Comment by devin-petersohn** [comment]
Superceded by #2622

**Pull request closed without merging**
