### PR TITLE
os.popen(cmd) # Noncompliant

### LINKED ISSUE #4980: REFACTOR: delete `build-docker.py` as it's unused currently
We also have no plans to use this file in the future.

### PR DESCRIPTION
**Pull request by gellanyhassan0**
Applications that execute operating system commands or execute commands that interact with the underlying system should neutralize any externally-provided values used in those commands. Failure to do so could allow an attacker to include input that executes unintended commands or exposes sensitive data.

Closes #4980

### CODE REVIEW

**Review by pyrito — COMMENTED** [review]
Thanks for opening this PR @gellanyhassan0 !

@modin-project/modin-contributors @modin-project/modin-core do we even use `teamcity` for CI anymore?

**Comment by Garra1980** [comment]
> Thanks for opening this PR @gellanyhassan0 !
> 
> @modin-project/modin-contributors @modin-project/modin-core do we even use `teamcity` for CI anymore?

Nope

**Comment by pyrito** [comment]
@Garra1980 should we remove the code for it? I don't see a point in merging in this PR if it's something we don't even use anymore.

**Comment by Garra1980** [comment]
> @Garra1980 should we remove the code for it? I don't see a point in merging in this PR if it's something we don't even use anymore.


Not sure, I'll let @anmyachev chime in here

**Comment by anmyachev** [comment]
@pyrito @Garra1980 [build-docker.py](https://github.com/modin-project/modin/blob/master/ci/teamcity/build-docker.py) and [comment_on_pr.py](https://github.com/modin-project/modin/blob/master/ci/teamcity/comment_on_pr.py) can be removed. However, [Dockerfile.teamcity-ci](https://github.com/modin-project/modin/blob/master/ci/teamcity/Dockerfile.teamcity-ci) is used for ASV benchmarking.

**Comment by gellanyhassan0** [comment]
> @pyrito @Garra1980 [build-docker.py](https://github.com/modin-project/modin/blob/master/ci/teamcity/build-docker.py) and [comment_on_pr.py](https://github.com/modin-project/modin/blob/master/ci/teamcity/comment_on_pr.py) can be removed. However, [Dockerfile.teamcity-ci](https://github.com/modin-project/modin/blob/master/ci/teamcity/Dockerfile.teamcity-ci) is used for ASV benchmarking.

am agree to remove build-docker.py and convert it to bash script to avoid security bug or delete it forever if have equivalent safe context build-docker.py

**Comment by anmyachev** [comment]
> > @pyrito @Garra1980 [build-docker.py](https://github.com/modin-project/modin/blob/master/ci/teamcity/build-docker.py) and [comment_on_pr.py](https://github.com/modin-project/modin/blob/master/ci/teamcity/comment_on_pr.py) can be removed. However, [Dockerfile.teamcity-ci](https://github.com/modin-project/modin/blob/master/ci/teamcity/Dockerfile.teamcity-ci) is used for ASV benchmarking.
> 
> am agree to remove build-docker.py and convert it to bash script to avoid security bug or delete it forever if have equivalent safe context build-docker.py

@gellanyhassan0 thanks for pointing this out, I'd appreciate it if you could delete `build-docker.py` file, that's enough for now.

**Comment by gellanyhassan0** [comment]
> > > @pyrito @Garra1980 [build-docker.py](https://github.com/modin-project/modin/blob/master/ci/teamcity/build-docker.py) and [comment_on_pr.py](https://github.com/modin-project/modin/blob/master/ci/teamcity/comment_on_pr.py) can be removed. However, [Dockerfile.teamcity-ci](https://github.com/modin-project/modin/blob/master/ci/teamcity/Dockerfile.teamcity-ci) is used for ASV benchmarking.
> > 
> > 
> > am agree to remove build-docker.py and convert it to bash script to avoid security bug or delete it forever if have equivalent safe context build-docker.py
> 
> @gellanyhassan0 thanks for pointing this out, I'd appreciate it if you could delete `build-docker.py` file, that's enough for now.

@anmyachev please help me why PR action fail in ci-required / lint (commit) (pull_request)

**Comment by anmyachev** [comment]
> > > > @pyrito @Garra1980 [build-docker.py](https://github.com/modin-project/modin/blob/master/ci/teamcity/build-docker.py) and [comment_on_pr.py](https://github.com/modin-project/modin/blob/master/ci/teamcity/comment_on_pr.py) can be removed. However, [Dockerfile.teamcity-ci](https://github.com/modin-project/modin/blob/master/ci/teamcity/Dockerfile.teamcity-ci) is used for ASV benchmarking.
> > > 
> > > 
> > > am agree to remove build-docker.py and convert it to bash script to avoid security bug or delete it forever if have equivalent safe context build-docker.py
> > 
> > 
> > @gellanyhassan0 thanks for pointing this out, I'd appreciate it if you could delete `build-docker.py` file, that's enough for now.
> 
> @anmyachev please help me why PR action fail in ci-required / lint (commit) (pull_request) after delete build-docker.py

Sure!

We have a set of commit requirements. The first commit must use one of the predefined prefixes (In your case, this is `REFACTOR-#4980:`).
I also want to ask you to sign the commit, this can be done with `-s` option of `git command`. For example: `git commit -s -m "REFACTOR-#4980: delete build-docker.py"`

**Review by pyrito — COMMENTED** [review]
@gellanyhassan0 please follow the contributing guidelines mentioned here: https://modin.readthedocs.io/en/stable/development/contributing.html. You should open a Github issue and then have your commit message refer to this issue.

**Comment by gellanyhassan0** [comment]
REFACTOR-#4980:  delete build-docker.py

**Pull request closed without merging**
