### PR TITLE
STY: rename view/mask to take_2d and take_2d_labels_or_positional

### LINKED ISSUE #4729: STY: rename QueryCompiler.view to something more consistent
QueryCompiler.view seems to behave more like PandasDataframe.mask (which in turn is completely different from pandas.DataFrame.mask).

I propose that both QueryCompiler.view and PandasDataframe.mask (and whatever other relevant methods are out there) be renamed to something like `take_2d` or possibly `take_or_slice_2d`

### PR DESCRIPTION
**Pull request by jbrockmendel**
- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
- [x] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] signed commit with `git commit -s` 
- [x] Resolves #4729
- [ ] tests added and passing
- [x] module layout described at `docs/development/architecture.rst` is up-to-date 
- [ ] added (Issue Number: PR title (PR Number)) and github username to release notes for next major release

### CODE REVIEW

**Comment by RehanSD** [comment]
PR looks good to me, but this does change our algebra (mask is considered an algebra operator). Should we just reframe and say that take is the algebra operator @devin-petersohn? Take makes less sense as an algebra name to me since I think mask has intuition behind it, but take does make sense in this case since Modin frames are immutable, and it parallels pandas.

**Comment by mvashishtha** [comment]
@RehanSD

> since I think mask has intuition behind it

In my view, "mask" does evoke "boolean masking", which is similar to what these functions do, but on the other hand these functions are very different from pandas `mask`, so I prefer the names here.

>  this does change our algebra

I think it's fine for academic terms for operators to be different from the names in implementation :)

**Comment by RehanSD** [comment]
> @RehanSD
> 
> 
> 
> > since I think mask has intuition behind it
> 
> 
> 
> In my view, "mask" does evoke "boolean masking", which is similar to what these functions do, but on the other hand these functions are very different from pandas `mask`, so I prefer the names here.
> 
> 
> 
> >  this does change our algebra
> 
> 
> 
> I think it's fine for academic terms for operators to be different from the names in implementation :) 

Hmm that makes sense to me! I'll go ahead and put an approval on it!

**Comment by jbrockmendel** [comment]
just rebased.  based on today's call i think everyone is on board?

**Review by mvashishtha — APPROVED** [review]

**Comment by mvashishtha** [comment]
>  based on today's call i think everyone is on board?

Yep. 

@modin-project/modin-omnisci we need omnisci approval.

**Review by Garra1980 — APPROVED** [review]

**Review by devin-petersohn — APPROVED** [review]

**Pull request merged**
