### PR TITLE
TEST-#0000: use custom Distributed

### PR DESCRIPTION
**Pull request by anmyachev**
## What do these changes do?

In the custom version of this `Distributed`, we remove the call of `self._get_computation_code()`, which is called in `submit->_graph_to_futures`. `_get_computation_code` takes about 75% of the total call time of `submit` function and it looks like it's just collecting additional information that might not be collected in a non-debug mode. With this change, Dask tests are faster than Ray tests. It is interesting to try to propose to implement a mechanism that disables the call to this function in `Distributed` library itself.

- [x] first commit message and PR title follow format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
  > **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your last commit for the CI job that checks the PR title to pick up the new PR title.
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #? 
- [ ] tests added and passing
- [ ] module layout described at `docs/development/architecture.rst` is up-to-date

### CODE REVIEW

**Comment by mvashishtha** [comment]
@anmyachev this looks very promising. Should we try contributing this to dask?

**Comment by anmyachev** [comment]
> @anmyachev this looks very promising. Should we try contributing this to dask?

@mvashishtha I think we should at least suggest introducing an environment variable that would regulate the collection of information using `_get_computation_code` function. For Modin, this could only be enabled in debug mode.

I don't have time yet, but if someone has the opportunity, then he can start doing right now :)

**Comment by mvashishtha** [comment]
Okay, I filed https://github.com/dask/distributed/issues/7740 with dask/distributed

**Comment by mvashishtha** [comment]
@anmyachev how did you measure how long `_get_computation_code` took? Some dask tests, like ` MODIN_ENGINE=DASK python -m pytest -n 2  modin/pandas/test/dataframe/test_indexing.py`, are excruciatingly slow in CI as well as on my laptop.

**Comment by anmyachev** [comment]
> @anmyachev how did you measure how long `_get_computation_code` took? Some dask tests, like ` MODIN_ENGINE=DASK python -m pytest -n 2 modin/pandas/test/dataframe/test_indexing.py`, are excruciatingly slow in CI as well as on my laptop.

IIRC ran a full set of tests on Dask with https://pypi.org/project/pytest-profiling/.

**Pull request closed without merging**
