### PR TITLE
FIX-#6117: Add error checking at API level for `diff`

### LINKED ISSUE #6117: REFACTOR: Add error checking at API layer for df.diff()
this is part of https://github.com/ponder-org/modin-public/commit/2402cc17ca88e38066830a509d3e5a5bee02ab31

### PR DESCRIPTION
**Pull request by RehanSD**
## What do these changes do?

- [x] first commit message and PR title follow format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
  > **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your last commit for the CI job that checks the PR title to pick up the new PR title.
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #6117 ? 
- [ ] tests added and passing
- [ ] module layout described at `docs/development/architecture.rst` is up-to-date

### CODE REVIEW

**Review by devin-petersohn — COMMENTED** [review]
Let's add some sanity tests that these exceptions get thrown.

**Review by devin-petersohn — DISMISSED** [review]
Thanks for adding, LGTM!

**Review by vnlitvinov — APPROVED** [review]
LGTM!

**Comment by RehanSD** [comment]
Seems like `fold_axis` may have been used, since tests are now failing. Adding it back.

**Comment by vnlitvinov** [comment]
Huh, this breaks in CI quite hard...

**Comment by RehanSD** [comment]
Nvm - I think its breaking CI b/c the QC is now taking `axis` as a named argument, and so it doesn't get passed through.

**Review by devin-petersohn — APPROVED** [review]
LGTM, thanks @RehanSD !

**Pull request merged**
