### PR TITLE
FIX-#2614: Up python version for test jobs

### LINKED ISSUE #2614: Up python version for test jobs
### Describe the problem

pandas 1.2.0 supports Python 3.7.1 and higher. In order to avoid dependencies conflict for our jobs we need to up python version.

### PR DESCRIPTION
**Pull request by YarShev**
Signed-off-by: Igoshev, Yaroslav <yaroslav.igoshev@intel.com>

## What do these changes do?

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/CONTRIBUTING.html)
- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #2614  
- [x] tests passing

### CODE REVIEW

**Comment by dchigarev** [comment]
we should also bump up python version in `BaseOnPython` job

**Comment by YarShev** [comment]
Not really, we need to bump up python version in other places as well. I am currently testing that in #2596.

**Review by devin-petersohn — DISMISSED** [review]
Thanks @YarShev LGTM!

**Comment by devin-petersohn** [comment]
@YarShev TeamCity reports failures even though tests passed, any ideas?

**Comment by YarShev** [comment]
@devin-petersohn , I guess something went wrong with uploading coverage report to Codecov. Let's rerun the tests and see if the issue goes away.

**Comment by YarShev** [comment]
@devin-petersohn , yes, the issue is gone away.

**Review by devin-petersohn — APPROVED** [review]

**Pull request merged**
