### PR TITLE
TEST-#3878: add 'time_groupby_agg_nunique_dict' benchmark for OmniSci

### LINKED ISSUE #3878: add groupby benchmarks with dict aggregation for omnisci (nunique op)
It could not be added in #3711 due to an OOM error (should now be fixed for OmniSci).

### PR DESCRIPTION
**Pull request by anmyachev**
Signed-off-by: Anatoly Myachev <anatoly.myachev@intel.com>

## What do these changes do?

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] signed commit with `git commit -s` 
- [x] Resolves #3878 
- [ ] tests added and passing
- [ ] module layout described at `docs/developer/architecture.rst` is up-to-date

### CODE REVIEW

**Comment by anmyachev** [comment]
From `test-asv-benchmarks`:
```bash
2021-12-23T14:10:21.919148 E 57530 0 1 RelAlgExecutor.cpp:3407 Query execution failed with error ERR_OUT_OF_CPU_MEM: Not enough host memory to execute the query
               2021-12-23T14:10:21.919600 E 57530 0 0 DBHandler.cpp:1385 ERR_OUT_OF_CPU_MEM: Not enough host memory to execute the query
```
@fexolm what data shape should be used to avoid OOM (current MODIN_MEMORY `~1GB`, dataframe shape - `10_000, 10`)?

**Comment by dchigarev** [comment]
> From `test-asv-benchmarks`:
> 
> ```shell
> 2021-12-23T14:10:21.919148 E 57530 0 1 RelAlgExecutor.cpp:3407 Query execution failed with error ERR_OUT_OF_CPU_MEM: Not enough host memory to execute the query
>                2021-12-23T14:10:21.919600 E 57530 0 0 DBHandler.cpp:1385 ERR_OUT_OF_CPU_MEM: Not enough host memory to execute the query
> ```
> 
> what data shape should be used to avoid OOM (current MODIN_MEMORY `~1GB`, dataframe shape - `10_000, 10`)?

As far as I understand the benchmark would fail anyway in our CI since omnisci/omniscidb#710 hasn't been fixed in the OmniSci master yet (our CI uses official omnisci releases from conda-forge, not our fork from intel-ai).

**Comment by anmyachev** [comment]
> > From `test-asv-benchmarks`:
> > ```shell
> > 2021-12-23T14:10:21.919148 E 57530 0 1 RelAlgExecutor.cpp:3407 Query execution failed with error ERR_OUT_OF_CPU_MEM: Not enough host memory to execute the query
> >                2021-12-23T14:10:21.919600 E 57530 0 0 DBHandler.cpp:1385 ERR_OUT_OF_CPU_MEM: Not enough host memory to execute the query
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > what data shape should be used to avoid OOM (current MODIN_MEMORY `~1GB`, dataframe shape - `10_000, 10`)?
> 
> As far as I understand the benchmark would fail anyway in our CI since [omnisci/omniscidb#710](https://github.com/omnisci/omniscidb/issues/710) hasn't been fixed in the OmniSci master yet (our CI uses official omnisci releases from conda-forge, not our fork from intel-ai). So we probably should put some kind of expected-to-fail modifier for this benchmark.

Thanks @dchigarev. Good catch!
I think it's not worth it, let's wait until the changes get into the conda package.

**Comment by dchigarev** [comment]
> let's wait until the changes get into the conda package.

It actually may take a lot, we even haven't sent a fixing PR to the OmniSci master yet 😄

**Comment by anmyachev** [comment]
not actual

**Pull request closed without merging**
