### PR TITLE
FIX-#4589: Pin protobuf<4.0.0 to fix ray.

### LINKED ISSUE #4589: CI downloads protobuf 4.21.1 and ray 1.12.1, which are incompatible.
See [this comment](https://github.com/ray-project/ray/issues/25638#issuecomment-1154422416). We should pin protobuf<4 to fix this bug.

### PR DESCRIPTION
**Pull request by mvashishtha**
Signed-off-by: mvashishtha <mahesh@ponder.io>

## What do these changes do?

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
- [x] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] signed commit with `git commit -s` 
- [x] Resolves #4589
- [x] tests added and passing
- [x] module layout described at `docs/development/architecture.rst` is up-to-date 
- [x] added (Issue Number: PR title (PR Number)) and github username to release notes for next major release

### CODE REVIEW

**Review by pyrito — APPROVED** [review]

**Review by RehanSD — COMMENTED** [review]
Should we add this to the env no engine yaml? @YarShev sufgested doing so on the last PR. Besides that, LGTM!

**Comment by mvashishtha** [comment]
@RehanSD, @YarShev says [here](https://github.com/modin-project/modin/pull/4499#discussion_r882438096) that he wants to pin the protobuf level there because that file is used in the test `test-ray-master`, but ray master already requires protobuf < 4.0.0, as I mentioned [here](https://github.com/ray-project/ray/issues/25638#issuecomment-1154422416).

**Comment by RehanSD** [comment]
> @RehanSD, @YarShev says [here](https://github.com/modin-project/modin/pull/4499#discussion_r882438096) that he wants to pin the protobuf level there because that file is used in the test `test-ray-master`, but ray master already requires protobuf < 4.0.0, as I mentioned [here](https://github.com/ray-project/ray/issues/25638#issuecomment-1154422416).

Makes sense to me!

**Review by RehanSD — APPROVED** [review]
LGTM!

**Pull request merged**
