### PR TITLE
PERF-#4886: Use lazy index and columns evaluation in `query` method

### LINKED ISSUE #4886: PERF: `dataframe.filter` can use lazy index and columns evaluation
Place: https://github.com/modin-project/modin/blob/fbd1e2a1b91170a3c45ce9565b1051bb2d55e4eb/modin/core/dataframe/pandas/dataframe/dataframe.py#L1799

We can avoid following call: https://github.com/modin-project/modin/blob/fbd1e2a1b91170a3c45ce9565b1051bb2d55e4eb/modin/core/dataframe/pandas/dataframe/dataframe.py#L1833

### PR DESCRIPTION
**Pull request by anmyachev**
## What do these changes do?

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
- [x] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] signed commit with `git commit -s` 
- [x] Resolves #4886 
- [x] tests added and passing
- [x] module layout described at `docs/development/architecture.rst` is up-to-date 
- [x] added (Issue Number: PR title (PR Number)) and github username to release notes for next major release

### CODE REVIEW

**Review by pyrito — COMMENTED** [review]
How much of a performance boost are we seeing for this?

**Comment by anmyachev** [comment]
> How much of a performance boost are we seeing for this?

Here we do not wait for this operation to be completed, but can immediately proceed to the next one. Thus, we save time by 90%(or more) of this function.

**Comment by pyrito** [comment]
Ah right, that was a dumb comment I made I guess. We are doing this lazy now, so we won't see a performance boost directly.

**Review by pyrito — APPROVED** [review]

**Comment by YarShev** [comment]
I already tried these changes on the workload we are profiling. There is a speed up both in the single node (~7 sec) and in the cluster (~8 sec).

**Review by YarShev — APPROVED** [review]

**Pull request merged**
