### PR TITLE
TEST-#2702: add loc/iloc benchmark

### LINKED ISSUE #2702: [ASV] add loc/iloc benchmark

### PR DESCRIPTION
**Pull request by anmyachev**
Signed-off-by: Anatoly Myachev <anatoly.myachev@intel.com>

## What do these changes do?

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [ ] passes `flake8 modin`
- [ ] passes `black --check modin`
- [ ] signed commit with `git commit -s` 
- [x] Resolves #2702 
- [ ] tests added and passing

### CODE REVIEW

**Comment by gshimansky** [comment]
I suggest that we add some of the complex variants of selection when both rows and columns are selected from a multiindex dataframe. Here is a work in progress on adding such tests https://github.com/modin-project/modin/compare/master...gshimansky:issue-2576
I also attach a notebook with even weirder experiments on `loc` syntax.
[multiindex_loc.ipynb.gz](https://github.com/modin-project/modin/files/5945281/multiindex_loc.ipynb.gz)

**Comment by anmyachev** [comment]
> I suggest that we add some of the complex variants of selection when both rows and columns are selected from a multiindex dataframe. Here is a work in progress on adding such tests [master...gshimansky:issue-2576](https://github.com/modin-project/modin/compare/master...gshimansky:issue-2576)
> I also attach a notebook with even weirder experiments on `loc` syntax.
> [multiindex_loc.ipynb.gz](https://github.com/modin-project/modin/files/5945281/multiindex_loc.ipynb.gz)

@gshimansky added multiindex loc test

**Comment by anmyachev** [comment]
@gshimansky ready for review.

**Review by gshimansky — APPROVED** [review]
LGTM

**Pull request merged**
