### PR TITLE
FIX-#3138: Fix consistency in connecting to Ray cluster and local cluster

### LINKED ISSUE #3138: Fix consistency in connecting to Ray cluster and local cluster
We work around a couple of things that users have seen in terms of using Ray and local python environments. However, we are not consistent with how we handle these for existing clusters. #3128 was a start toward this, but we also have a case where the `typing` library from pypi can fall before the Python builtin library causing errors.

We need to move these lines outside of the if block to handle them the same between both existing clusters and local clusters: 

https://github.com/modin-project/modin/blob/8165051b1bafb1b6dc3cc6069449637c60071f66/modin/engines/ray/utils.py#L218-L221

cc @YarShev

### PR DESCRIPTION
**Pull request by YarShev**
Signed-off-by: Igoshev, Yaroslav <yaroslav.igoshev@intel.com>

## What do these changes do?

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #3138  
- [ ] tests added and passing
- [x] module layout described at `docs/developer/architecture.rst` is up-to-date

### CODE REVIEW

**Review by devin-petersohn — APPROVED** [review]
Thanks @YarShev, LGTM!

**Comment by devin-petersohn** [comment]
@YarShev conda in test environment is causing some issues again. I will restart CI.

**Comment by YarShev** [comment]
@devin-petersohn , something went wrong with `modin/experimental/sql/test/test_sql.py`. I restarted CI to see whether the issue persists or not.

**Comment by YarShev** [comment]
@devin-petersohn , CI is green.

**Review by vnlitvinov — APPROVED** [review]
LGTM

**Review by devin-petersohn — APPROVED** [review]

**Pull request merged**
