### PR TITLE
FIX-#4105: fix names of pandas options to avoid OptionError 

### PR DESCRIPTION
**Pull request by paulovn**
## What do these changes do?

fixes https://github.com/modin-project/modin/issues/4105

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/developer/contributing.html#commit-message-formatting)
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] signed commit with `git commit -s` 
- [x] Resolves #? 
- [ ] tests added and passing
- [ ] module layout described at `docs/development/architecture.rst` is up-to-date 
- [x] added (Issue Number: PR title (PR Number)) and github username to release notes for next major release

### CODE REVIEW

**Comment by RehanSD** [comment]
Hi @paulovn ! Thank you so much for opening a PR for this! As a quick note, we usually ask our contributors to name their PRs with the following convention: {FIX|FEAT|DOCS|REFACTOR|TEST}-#{ISSUE_NUMBER}: {PR TITLE}, and make the first commit in the PR follow this convention, as well as be signed off, which you can accomplish via `git commit -s ...` You can read more about our contributing guidelines in our (docs)[https://modin.readthedocs.io/en/stable/development/contributing.html]!

Would you mind updating the PR title as well as the first commit, with `FIX-#4105: ...`?

Additionally, could you please add your PR title and your GitHub username to our release notes template found [here](https://github.com/modin-project/modin/blob/master/docs/release_notes/release_notes-0.14.0.rst), as described in #4078 so we can make sure to credit you when we release!

**Review by RehanSD — APPROVED** [review]
Awesome work! Happy to merge once title + release notes are updated!

**Comment by paulovn** [comment]
Ok, I believe the names of commits, PR and release notes are now compliant with the guidelines.

BTW, you may want to correct the automatic template for a PR, the link to the instructions for naming is broken. Where it says

>commit message follows format outlined here

... i believe the link includes _latest_ but it should say _stable_. I clicked on it but didn't get anything, so I couldn't follow the convention

**Comment by RehanSD** [comment]
> Ok, I believe the names of commits, PR and release notes are now compliant with the guidelines.
> 
> 
> 
> BTW, you may want to correct the automatic template for a PR, the link to the instructions for naming is broken. Where it says
> 
> 
> 
> >commit message follows format outlined here
> 
> 
> 
> ... i believe the link includes _latest_ but it should say _stable_. I clicked on it but didn't get anything, so I couldn't follow the convention

Thank you for the changes, and for pointing out the broken link! I'll be sure to add a PR to fix that! PR looks great, so I'll go ahead and merge - thank you!

**Review by RehanSD — APPROVED** [review]
LGTM!

**Review by devin-petersohn — APPROVED** [review]

**Comment by devin-petersohn** [comment]
Thanks @paulovn!

`black` pushed a new version, so those failures are unrelated to this PR.

**Comment by devin-petersohn** [comment]
@paulovn Are you able to rebase on master? We had some unlucky timing with multiple new versions of libraries dropping around the same time, but everything should be fixed.

**Comment by paulovn** [comment]
Yep, done. The patch is tiny, so there is no big deal

**Review by RehanSD — DISMISSED** [review]
Thank you for contributing - the PR looks great, and I'm happy to merge once CI is green!

**Review by RehanSD — APPROVED** [review]
LGTM

**Pull request merged**
