### PR TITLE
Add trailing commas

### LINKED ISSUE #1546: Add trailing commas to satisfy black code style
Black about trailing commas: [link](https://test-black.readthedocs.io/en/style-guide/style_guide/trailing_commas.html)

Going on black code style all python files that 3.6+ should have trailing commas to expressions that are split by comma where each element is on its own line. But not all files follow that rules. Because not all of the files have 3.6+ traits to black could detect if it should or not add trailing comma, it doesn't fail on current master

### PR DESCRIPTION
**Pull request by dchigarev**
Signed-off-by: Dmitry Chigarev <dmitry.chigarev@intel.com>

## What do these changes do?

- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #1546 
- [ ] tests added and passing

see [#1524](https://github.com/modin-project/modin/pull/1524#issuecomment-638301122)

### CODE REVIEW

**Comment by anmyachev** [comment]
@devin-petersohn can we extend this style to the whole modin, and not just to this file `modin/pandas/dataframe.py`?

**Comment by devin-petersohn** [comment]
@anmyachev Yes we should do it everywhere.

Is black failing for others on other files? Why is this the only file affected?

**Comment by dchigarev** [comment]
@devin-petersohn [trailing commas in black](https://test-black.readthedocs.io/en/style-guide/style_guide/trailing_commas.html)
the last paragraph is interested for us, black adds extra comma only if file for Python 3.6+, if `.py` file has some traits of 3.6+ (like format strings, which was added at `dataframe.py` in #1524) black suppose to add it.

It seems that some files doesn't have traits of 3.6+ that's why only `dataframe.py` was affected

**Comment by devin-petersohn** [comment]
Thanks @dchigarev, I have just realized a serious issue and we cannot do this.

We are supporting also python 3.5, which doesn't support trailing commas: https://github.com/modin-project/modin/blob/master/setup.py#L68

We must support all python versions that pandas supports, so I do not think we can update the trailing commas until we move to only python 3.6+.

**Comment by dchigarev** [comment]
@devin-petersohn, pandas 1.0.3 (which is required to use modin) seems to works only at python versions that greater than 3.6.1: https://github.com/pandas-dev/pandas/blob/master/setup.py#L774

so It seems no problems to update modin to 3.6+ only

**Comment by devin-petersohn** [comment]
I see, good catch. I must have been going on an older version and did not update it.

Let me fix a couple of things in the `setup.py`, then we can add this. We need to update the versions of some dependencies as well.

We should wait until we fix the python version in setup.py so we do not have a commit that breaks for Python 3.5.

**Comment by dchigarev** [comment]
done it at #1551

**Comment by devin-petersohn** [comment]
Great, left a comment on that one.

**Comment by dchigarev** [comment]
@devin-petersohn since #1551 are merged, this PR is ready to merge

**Pull request merged**
