### PR TITLE
DOCS-#0000: Update RunLLM Ask AI widget path

### PR DESCRIPTION
**Pull request by likawind**
## What do these changes do?

This PR to updates the widget's script path. RunLLM has switched to a new deployment framework which resolved multiple package delivery issues caused by jscdn caching. This improvement ensures RunLLM's askAI widget is more consistently up-to-date.

- [x] first commit message and PR title follow format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
  > **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your last commit for the CI job that checks the PR title to pick up the new PR title.
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #? 
- [ ] tests added and passing
- [ ] module layout described at `docs/development/architecture.rst` is up-to-date

### CODE REVIEW

**Review by YarShev — APPROVED** [review]
@likawind, thanks!

**Comment by YarShev** [comment]
@likawind, could you correct the commit message to be in line with [our rules for commits](https://modin.readthedocs.io/en/stable/development/contributing.html#commit-message-formatting)?

**Comment by likawind** [comment]
@YarShev thanks for updating the PR title. I also redo the commit and corrected the message

**Review by devin-petersohn — APPROVED** [review]

**Comment by YarShev** [comment]
@likawind, you should also sign off your commit message. Could you ping us when you do this?

**Comment by likawind** [comment]
@YarShev thank you! Updated the commit message, lmk if you have any other suggestions

**Review by YarShev — APPROVED** [review]
@likawind, LGTM, thanks!

**Pull request merged**
