### PR TITLE
Switch to Ray from conda-forge

### LINKED ISSUE #2561: Move to Ray from conda-forge in the environment to speed things up
This should speed up the testing a little bit by speeding up environment set up.

### PR DESCRIPTION
**Pull request by vnlitvinov**
Signed-off-by: Vasilij Litvinov <vasilij.n.litvinov@intel.com>

## What do these changes do?

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/CONTRIBUTING.html)
- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #2561
- [ ] tests added and passing

### CODE REVIEW

**Comment by amyskov** [comment]
Looks good, but what about  `.github/workflows/push.yml` file?

**Comment by vnlitvinov** [comment]
Good point, I forgot about that. Will fix now.

**Comment by amyskov** [comment]
Also docker files for benchmark running contains explicit ray installation (https://github.com/modin-project/modin/blob/master/examples/docker/census-on-omnisci/census-omnisci.dockerfile#L51), can it be removed now?

**Comment by vnlitvinov** [comment]
> Also docker files for benchmark running contains explicit ray installation (https://github.com/modin-project/modin/blob/master/examples/docker/census-on-omnisci/census-omnisci.dockerfile#L51), can it be removed now?

This is a completely separate issue, and it can not be removed right now, because we saw cases when just installing `modin` without asking for `ray` brings us conda-forge modin without Omnisci.

This file would have to be fixed after our modin moves to conda-forge ray, too (cc @anmyachev), and we push a release.

**Review by amyskov — APPROVED** [review]

**Pull request merged**
