### PR TITLE
Release version 0.16.0

### PR DESCRIPTION
**Pull request by mvashishtha**
Release version 0.16.0

### CODE REVIEW

**Review by RehanSD — DISMISSED** [review]
LGTM!

**Review by pyrito — COMMENTED** [review]
Is this PR just an empty commit for the repo tag?

**Comment by RehanSD** [comment]
> Is this PR just an empty commit for the repo tag?

Yup - we're dropping 0.16 right now!

**Review by RehanSD — APPROVED** [review]
LGTM!

**Pull request merged**
