### PR TITLE
PERF-#6694: Use lazy_map_partitions() for dtypes conversion

### LINKED ISSUE #6694: PERF: Use lazy_map_partitions() for dtypes conversion
The code below is ~6 times faster if `lazy_map_partitions()` is used by `astype()`.

```python
import timeit
import modin.pandas as pd
import ray

ray.init()

df = pd.DataFrame({i: range(1000) for i in range(100)})
def test():
    for c in df.columns:
        df[c] = df[c].astype(float)
    df.shape
time = timeit.timeit(test, number=1)
print(f"Time: {time}")
```

### PR DESCRIPTION
**Pull request by AndreyPavlenko**
## What do these changes do?

- [x] first commit message and PR title follow format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
  > **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your last commit for the CI job that checks the PR title to pick up the new PR title.
- [x] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] signed commit with `git commit -s` 
- [x] Resolves #6694 
- [ ] tests added and passing
- [ ] module layout described at `docs/development/architecture.rst` is up-to-date

### CODE REVIEW

**Review by anmyachev — APPROVED** [review]
LGTM!

**Comment by dchigarev** [comment]
Just wanted to mention, that using of `lazy_map_partitions()` can bring unexpected side effects. In modin, we don't have any mechanism that would prevent lazy functions to be run multiple times, which most of the time leads to that lazy functions being actually executed multiple times, thus giving the opposite effect of what we wanted by slowing down the code. This is the exact reason why we removed almost all `.lazy_map_partitions()` calls in #2471 and then raised #5809 to figure out a proper solution.

To reproduce the problem of double-execution, consider this modified example of the reproducer from #6694:
```python
from timeit import default_timer as timer
import modin.pandas as pd
import ray
from modin.utils import execute

ray.init()

df = pd.DataFrame({i: range(1000) for i in range(100)})
t1 = timer()
for c in df.columns:
    df[c] = df[c].astype(float)
# df execution call queue: [.astype()]

r1 = df.sum()
# r1 execution call queue: [.astype(), .sum()]

r2 = df.mean()
# r2 execution call queue: [.astype(), .mean()]

r3 = df.sort_values(df.columns[0])
# r3 execution call queue: [.astype(), .sort_values()]

execute(r3) # calls '.astype()' and '.sort_values()'
execute(r2) # calls '.astype()' and '.mean()'
execute(r1) # calls '.astype()' and '.sum()'
execute(df) # calls '.astype()'

print(f"Time: {timer() - t1}")
```

As you can see, here we would call '.astype()' on all columns 4 times, however, we only wanted for this to be called once. Then measuring this example gives the following:
|test case|before this PR|after this PR|
|-|-|-|
|original test case from #6694|12.3|9.65|
|modified test case from this comment|15.45|25.94|

**Comment by anmyachev** [comment]
@dchigarev the same logic applies to how we assign new indexes, why wasn't it removed #2471? (Because we have a propagation mechanism?)

It's probably worth rolling back the change again. @AndreyPavlenko what do you think?

**Comment by AndreyPavlenko** [comment]
> It's probably worth rolling back the change again. @AndreyPavlenko what do you think?

If there is no a quick fix for `lazy_map_partitions()` then, probably, it makes sense to revert.
Or, may be, revert only if this PR caused benchmarks perf degradation?

**Comment by dchigarev** [comment]
> the same logic applies to how we assign new indexes, why wasn't it removed

I believe it's because index propagation is fairly simple operation, and it gives almost unnoticeable overhead on running it multiple times

**Comment by AndreyPavlenko** [comment]
> I believe it's because index propagation is fairly simple operation, and it gives almost unnoticeable overhead on running it multiple times

The remote call overhead could be noticeable. Could we add some logic in `lazy_map_partitions()` to make the remote call only once and then cache the result and return it on subsequent calls?

**Comment by dchigarev** [comment]
> The remote call overhead could be noticeable.

`lazy_map_partitions()` doesn't make any remote calls, it just takes an input function and stores it in order to combine it with any following non-lazy function and submit them as a one kernel:
```python
df # call_queue: []
df = df.lazy_map_partitions(func1) # call_queue: [func1]
df = df.map_partitions(func2) # a non-lazy function was applied, combining 'func1' and 'func2' and submiting the kernel:
# @ray.remote
# def kernel(df):
#     return func2(func1(df))
# result = kernel.remote(df)
```

The problem of double-computation means, that inside of every kernel being submitted against 'df', the 'func1' will always be called:
```python
df # call_queue: []
df = df.lazy_map_partitions(func1) # call_queue: [func1]
r1 = df.map_partitions(func2) # submit kernel = lambda df: func2(func1(df))
r2 = df.map_partitions(func3) # submit kernel = lambda df: func3(func1(df))
```
It shouldn't be a problem if 'func1' is relatively small and fast (like the mentioned example with index propagation), however, it's not the case when 'func1' appears to be a quite heavy function (like 'astype')

**Comment by AndreyPavlenko** [comment]
> `lazy_map_partitions()` doesn't make any remote calls

Yes, I understand that. Could we use, for example, some wrapper for each function? When it's submitted for execution the first time, the result is cached and returned on the subsequent submissions.

**Comment by dchigarev** [comment]
Something like this?
```python
@ray.remote
def kernels_submiter(df, *funcs):
    results = []
    for func in funcs:
        df = func(df)
        results.append(df)
    return results

r1 = df.map_partitions(func2) 
# func1_res, func2_res = kernel_submiter.remote(df, func1, func2)   
# df.assign_result(func1_res) # it now has call_queue: []
# r1.assign_result(func2_res)
r2 = df.map_partitions(func3) # since we already assigned the result for 'df' we no longer
                              # need to submit func1
```
This will require some development efforts, however, should solve the double-computation problem. The only thing that bothers me is that the size of the kernel's return value will double and so this can affect performance of putting the result to the plasma storage

**Comment by AndreyPavlenko** [comment]
> To reproduce the problem of double-execution, consider this modified example of the reproducer from #6694:

With this https://github.com/modin-project/modin/pull/6731 PR the result is much better - 5.7.

**Pull request merged**
