### PR TITLE
FIX-#3899: Add pyright config.

### LINKED ISSUE #3899: Integrate pyright type checking
For https://github.com/modin-project/modin/issues/74 adding type hints to the modin repo, it's helpful to integrate a type checker so that we can incrementally and consistently update the codebase. [pyright](https://github.com/microsoft/pyright) is a good option for this, as [simon-mo mentioned here](https://github.com/modin-project/modin/issues/74#issuecomment-577320843).

To integrate pyright, we need to add a [pyrightconfig.json](https://github.com/microsoft/pyright/blob/main/docs/configuration.md) to the repo, recommend that modin contributors install pyright, either:
- as a [VSCode extension](https://github.com/microsoft/pyright#vs-code-extension)
  - both [pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) and [python in vscode](https://marketplace.visualstudio.com/items?itemName=ms-python.python) run pyright in the backend
- via [pip/conda](https://github.com/microsoft/pyright#command-line)
- vim/emacs/sublime text also have support

Then we should add pyright to our CI via presumbit check, see [pyright docs](https://github.com/microsoft/pyright/blob/main/docs/ci-integration.md) and our [contributing section](https://github.com/modin-project/modin/tree/master/contributing).

### PR DESCRIPTION
**Pull request by jeffreykennethli**
Signed-off-by: jeffreykennethli <jkli@ponder.io>

## What do these changes do?

Adds a [pyrightconfig.json file](https://github.com/microsoft/pyright/blob/main/docs/configuration.md) that specifies the pyright options we want to use for Modin. Pyright has three strictness levels: `off`, `basic`, and `strict`. We can start with `off` level and fix all the errors and warnings, then gradually move up.

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #3899? 
- [ ] tests added and passing
- [ ] module layout described at `docs/developer/architecture.rst` is up-to-date

### CODE REVIEW

**Review by devin-petersohn — COMMENTED** [review]
@jeffreykennethli thanks for the PR!

Should we add pyright to the CI as well? Or at least add some instruction for how to use pyright in the developer docs?

**Comment by vnlitvinov** [comment]
I would rather this PR would add at least one CI check for one file, because as it is now this is "some config for some tool" conveying no idea on how to use that.

**Review by devin-petersohn — COMMENTED** [review]
@jeffreykennethli let's add pyright to the CI in this PR.

**Comment by jeffreykennethli** [comment]
Superceded by MyPy: https://github.com/modin-project/modin/issues/4619

**Pull request closed without merging**
