### PR TITLE
FIX-#4658: Expand exception handling for `read_*` functions from s3 storages

### LINKED ISSUE #4658: `read_csv` throws error during reading from s3
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 11
- **Modin version** (`modin.__version__`): 06ec64bedc2ace639af09759053182472fdd6544
- **Python version**: 3.8.13
- **Code we can use to reproduce**:

```python
import modin.pandas as pd

s3_path = "s3://dask-data/nyc-taxi/2015/yellow_tripdata_2015-01.csv"
df = pd.read_csv(s3_path, parse_dates=["tpep_pickup_datetime", "tpep_dropoff_datetime"], nrows=10,  storage_options={"anon": True})
print(df)

```

### Describe the problem
`read_csv` throws error during reading from s3. The root cause is unhandled exception here: https://github.com/modin-project/modin/blob/eddfda4b521366c628596dcb5c21775c7f50eec1/modin/core/io/file_dispatcher.py#L276

### Source code / logs

```shell
File "C:\Users\79049\Documents\projects\modin\modin\core\io\text\text_file_dispatcher.py", line 641, in check_parameters_support
    if not cls.file_exists(
  File "C:\Users\79049\Documents\projects\modin\modin\logging\logger_decorator.py", line 128, in run_and_log
    return obj(*args, **kwargs)
  File "C:\Users\79049\Documents\projects\modin\modin\core\io\file_dispatcher.py", line 275, in file_exists
    exists = s3fs.exists(file_path) or exists
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\fsspec\asyn.py", line 86, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\fsspec\asyn.py", line 66, in sync
    raise return_result
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\fsspec\asyn.py", line 26, in _runner
    result[0] = await coro
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\s3fs\core.py", line 888, in _exists
    await self._info(path, bucket, key, version_id=version_id)
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\s3fs\core.py", line 1140, in _info
    out = await self._call_s3(
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\s3fs\core.py", line 325, in _call_s3
    await self.set_session()
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\s3fs\core.py", line 473, in set_session
    self._s3 = await s3creator.__aenter__()
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\aiobotocore\session.py", line 22, in __aenter__
    self._client = await self._coro
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\aiobotocore\session.py", line 102, in _create_client
    credentials = await self.get_credentials()
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\aiobotocore\session.py", line 133, in get_credentials
    self._credentials = await (self._components.get_component(
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\aiobotocore\credentials.py", line 814, in load_credentials
    creds = await provider.load()
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\aiobotocore\credentials.py", line 486, in load
    metadata = await fetcher.retrieve_iam_role_credentials()
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\aiobotocore\utils.py", line 175, in retrieve_iam_role_credentials
    token = await self._fetch_metadata_token()
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\aiobotocore\utils.py", line 88, in _fetch_metadata_token
    response = await session.send(request.prepare())
  File "C:\Users\79049\.conda\envs\modin\lib\site-packages\aiobotocore\httpsession.py", line 211, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://169.254.169.254/latest/api/token"
```

### PR DESCRIPTION
**Pull request by prutskov**
Signed-off-by: Alexey Prutskov <lehaprutskov@gmail.com>

## What do these changes do?

The PR expand the set of handled exceptions in `read_*` functions from s3 storages by `EndpointConnectionError` exception

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
- [x] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] signed commit with `git commit -s` 
- [x] Resolves #4658 
- [x] tests added and passing
- [x] module layout described at `docs/development/architecture.rst` is up-to-date 
- [x] added (Issue Number: PR title (PR Number)) and github username to release notes for next major release

### CODE REVIEW

**Comment by anmyachev** [comment]
@prutskov How does pandas handle `EndpointConnectionError` exception? A simple search for this exception in its source code turned up nothing.

**Comment by prutskov** [comment]
> @prutskov How does pandas handle `EndpointConnectionError` exception? A simple search for this exception in its source code turned up nothing.

I assume this exception is processed internally in `fsspec` module which `pandas`/`modin` use for getting of file objects. But we also use `s3fs.S3FileSystem` which can't handle this exception internally. That's reason why I added handling of this exception only for places of code where `s3fs.S3FileSystem` is used.

**Review by mvashishtha — APPROVED** [review]
@prutskov thanks, LGTM!

**Review by mvashishtha — APPROVED** [review]

**Comment by prutskov** [comment]
@modin-project/modin-core This PR has green CI and approvements from modin-core. Probably, you can merge this

**Review by mvashishtha — APPROVED** [review]

**Pull request merged**
