### PR TITLE
FIX-#2667: Change names of files for development env

### LINKED ISSUE #2667: Change name of files for testing conda/pip environment
### Describe the problem

Change names of environment files for `conda/pip`: `requirements.txt`->`test_requires.txt`, `environment.yml`->`test_environment.yml` as this envs are needed for development/testing but not for necessary installation by users.

### PR DESCRIPTION
**Pull request by prutskov**
Signed-off-by: Alexey Prutskov <alexey.prutskov@intel.com>

## What do these changes do?

This changes includes renaming of files which is used for creation of testing environment

**NOTE:** Need to change run commands in teamcity testing after this is merged.

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #2667

### CODE REVIEW

**Comment by anmyachev** [comment]
I would prefer such naming: `enviroment-dev.yml`, `requirements-dev.txt` and so on.

**Comment by prutskov** [comment]
@anmyachev Thanks, your suggestion was applied.

**Comment by anmyachev** [comment]
@prutskov please pay attention to TeamCity failed tests

**Comment by prutskov** [comment]
@anmyachev As I noticed in description, we should change our run scripts for teamcity after merge, because if we do this right now, all teamcity tests in other branches will be failed.

**Review by anmyachev — APPROVED** [review]

**Pull request merged**
