### PR TITLE
DOCS-#5402: Add warning about instability of sort

### LINKED ISSUE #5402: Update sort docs on stability
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. What kind of performance improvements would you like to see with this new API?
As per https://github.com/modin-project/modin/pull/4601/files#r1001233604, we want to warn users that our new sort is unstable for different index values that have the same sort key - so their order is not guaranteed to remain the same across runs.

### PR DESCRIPTION
**Pull request by RehanSD**
Signed-off-by: Rehan Durrani <rehan@ponder.io>

## What do these changes do?

- [x] first commit message and PR title follow format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
  > **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your last commit for the CI job that checks the PR title to pick up the new PR title.
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] signed commit with `git commit -s` 
- [x] Resolves #5402  
- [ ] tests added and passing
- [ ] module layout described at `docs/development/architecture.rst` is up-to-date

### CODE REVIEW

**Review by YarShev — COMMENTED** [review]
Why does the diff look so big? Did you add a note only for sort_values in tables?

**Comment by RehanSD** [comment]
My editor reformatted the table to be wider when I tried to break the note that I added - I can try and undo that!

**Comment by YarShev** [comment]
Yes, please try to introduce the changes only for sort_values rows.

**Review by YarShev — APPROVED** [review]
@RehanSD, thanks!

**Pull request merged**
