### PR TITLE
FEAT-#2949: Add `show_history` option to Spreadsheet API

### LINKED ISSUE #2949: Add `show_history` option to Spreadsheet API
Changes were made to the `modin_spreadsheet` API `show_grid`. Make corresponding changes on Spreadsheet API `from_dataframe`.

### PR DESCRIPTION
**Pull request by richardlin047**
## What do these changes do?
Makes corresponding changes in Spreadsheet API `from_dataframe` that matches changes in `modin_spreadsheet.show_grid` (https://github.com/modin-project/qgrid/pull/28). This adds the `show_history` parameter, which determines whether the history cell is displayed.

Also added a test that inputs a value for all parameters of `from_dataframe` just to check that it doesn't error.

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #2949 ? 
- [x] tests added and passing

### CODE REVIEW

**Comment by richardlin047** [comment]
Spreadsheet tests not passing because most recent release (v0.1.1) of modin-spreadsheet does not include changes yet.

**Review by devin-petersohn — COMMENTED** [review]
@richardlin047 Should we release a new version for `modin-spreadsheet`?

**Review by devin-petersohn — COMMENTED** [review]
@richardlin047 What is needed for this PR?

**Comment by richardlin047** [comment]
@devin-petersohn Nothing else needed for this PR, just needs to be reviewed.

**Review by devin-petersohn — APPROVED** [review]
LGTM, thanks @richardlin047!

**Pull request merged**
