### PR TITLE
FIX-#2508: Defaults to pandas for read_csv if `dialect!=None`

### LINKED ISSUE #2508: read_csv with Ray engine fails with `dialect` parameter
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Modin version**: ce2bea8867739ea792cdda0dce8ad50e366ebae1
- **Python version**: 3.8.6
- **Code we can use to reproduce**:
```
import os

os.environ["MODIN_ENGINE"] = "ray"

import pandas
import modin.pandas as pd
import csv
from modin.pandas.test.utils import df_equals

test_filename = "test.csv"
dialect_name = "test_dialect"


test_csv_dialect_params = {"delimiter": "|"}
csv.register_dialect(dialect_name, **test_csv_dialect_params)
dialect = csv.get_dialect(dialect_name)

kwargs = {
    "filepath_or_buffer": test_filename,
    "dialect": dialect,
}


test_data = """col1,col2,
1,2
3,4
"""

try:
    with open(test_filename, "w") as f:
        f.write(test_data)

    df_pandas = pandas.read_csv(**kwargs)
    print("pandas.read_csv output:\n", df_pandas)
    df_pd = pd.read_csv(**kwargs)
    print("pd.read_csv output:\n", df_pd)
    df_equals(df_pandas, df_pd)
finally:
    os.remove(test_filename)
```

### Source code / logs

```
pandas.read_csv output:
   col1,col2,
0        1,2
1        3,4
Traceback (most recent call last):
  File "test.py", line 242, in <module>
    df_pd = pd.read_csv(**kwargs)
  File "/modin/modin/pandas/io.py", line 109, in parser_func
    return _read(**kwargs)
  File "/modin/modin/pandas/io.py", line 127, in _read
    pd_obj = EngineDispatcher.read_csv(**kwargs)
  File "/modin/modin/data_management/factories/dispatcher.py", line 104, in read_csv
    return cls.__engine._read_csv(**kwargs)
  File "/modin/modin/data_management/factories/factories.py", line 87, in _read_csv
    return cls.io_cls.read_csv(**kwargs)
  File "/modin/modin/engines/base/io/file_dispatcher.py", line 29, in read
    query_compiler = cls._read(*args, **kwargs)
  File "/modin/modin/engines/base/io/text/csv_dispatcher.py", line 168, in _read
    partition_id = cls.deploy(cls.parse, num_splits + 2, args)
  File "/modin/modin/engines/ray/task_wrapper.py", line 25, in deploy
    return deploy_ray_func._remote(args=(func, kwargs), num_returns=num_returns)
  File "/miniconda3/envs/modin_new/lib/python3.8/site-packages/ray/remote_function.py", line 276, in _remote
    return invocation(args, kwargs)
  File "/miniconda3/envs/modin_new/lib/python3.8/site-packages/ray/remote_function.py", line 262, in invocation
    object_refs = worker.core_worker.submit_task(
  File "python/ray/_raylet.pyx", line 1019, in ray._raylet.CoreWorker.submit_task
  File "python/ray/_raylet.pyx", line 1025, in ray._raylet.CoreWorker.submit_task
  File "python/ray/_raylet.pyx", line 293, in ray._raylet.prepare_args
  File "/miniconda3/envs/modin_new/lib/python3.8/site-packages/ray/serialization.py", line 404, in serialize
    return self._serialize_to_msgpack(value)
  File "/miniconda3/envs/modin_new/lib/python3.8/site-packages/ray/serialization.py", line 384, in _serialize_to_msgpack
    self._serialize_to_pickle5(metadata, python_objects)
  File "/miniconda3/envs/modin_new/lib/python3.8/site-packages/ray/serialization.py", line 344, in _serialize_to_pickle5
    raise e
  File "/miniconda3/envs/modin_new/lib/python3.8/site-packages/ray/serialization.py", line 340, in _serialize_to_pickle5
    inband = pickle.dumps(
  File "/miniconda3/envs/modin_new/lib/python3.8/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 70, in dumps
    cp.dump(obj)
  File "/miniconda3/envs/modin_new/lib/python3.8/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 656, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle '_csv.Dialect' object
```

### PR DESCRIPTION
**Pull request by anmyachev**
Signed-off-by: Anatoly Myachev <anatoly.myachev@intel.com>

## What do these changes do?

If a csv' object is passed as a dialect, then Modin does not work, since this object is not serializable. If its name is passed as a dialect, then this dialect will not be found on the workers, since it is registered only in the main process.

- [x] first commit message and PR title follow format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
  > **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your last commit for the CI job that checks the PR title to pick up the new PR title.
- [x] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] signed commit with `git commit -s` 
- [x] Resolves #2508 
- [x] tests added and passing
- [x] module layout described at `docs/development/architecture.rst` is up-to-date

### CODE REVIEW

**Review by YarShev — APPROVED** [review]
Please resolve the conflict.

**Review by YarShev — APPROVED** [review]

**Comment by vnlitvinov** [comment]
TBH this PR looks more like a workaround rather than a fix... a true fix would be to make non-`None` `dialect` work in a parallel way. Is that completely impossible? If so it makes sense to add it to some place in Modin docs.

**Comment by anmyachev** [comment]
> TBH this PR looks more like a workaround rather than a fix... a true fix would be to make non-`None` `dialect` work in a parallel way. Is that completely impossible? If so it makes sense to add it to some place in Modin docs.

I fixed the correctness of the work - this is a fix, then what you are talking about is more like a performance fix. In my understanding, if we can at least make it work slowly - we should do it. It's still better.

I didn't have a chance to check if it can be done fast.

**Comment by YarShev** [comment]
To me it looks as a fix, and make it work in a distributed way is a feature. When we implement a pandas function that works in a distributed way, we treat it as a feature.

**Pull request merged**
