### PR TITLE
DOCS-#3922: Remove broken links from supported apis

### LINKED ISSUE #3922: Broken links in "Supported APIs" table
Some links to the pandas documentation are broken in the [Supported APIs page](https://modin.readthedocs.io/en/latest/supported_apis/dataframe_supported.html) and need to be updated (e.g., `as_blocks`, `as_matrix`, etc.)

### PR DESCRIPTION
**Pull request by susmitpy**
## What do these changes do?
Remove the following broken links from dataframe supported apis:
('as_blocks', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.as_blocks.html#pandas.DataFrame.as_blocks')
('as_matrix', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.as_matrix.html#pandas.DataFrame.as_matrix')
('blocks', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.blocks.html#pandas.DataFrame.blocks')
('clip_lower', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.clip_lower.html#pandas.DataFrame.clip_lower')
('clip_upper', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.clip_upper.html#pandas.DataFrame.clip_upper')
('from_items', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.from_items.html#pandas.DataFrame.from_items')
('ftypes', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.ftypes.html#pandas.DataFrame.ftypes')
('to_dense', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_dense.html#pandas.DataFrame.to_dense')
('to_msgpack', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_msgpack.html#pandas.DataFrame.to_msgpack')
('to_sparse', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_sparse.html#pandas.DataFrame.to_sparse')

Removes the following methods from series apis:

1. as_blocks
2. as_matrix
3. blocks
4. clip_lower
5. clip_upper
6. ftypes
7. to_dense
8. to_msgpack
9. to_sparse

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] signed commit with `git commit -s` 
- [x] Resolves #3922 
- [ ] tests added and passing
- [ ] module layout described at `docs/developer/architecture.rst` is up-to-date

### CODE REVIEW

**Comment by dchigarev** [comment]
@susmitpy Thanks for the changes! I also found that `series_supported.rst` also has the same [outdated methods](https://github.com/susmitpy/modin/blame/master/docs/supported_apis/series_supported.rst#L49-L51). Would you like them to be removed here or in a different PR?

**Comment by susmitpy** [comment]
@dchigarev 
I will have a look, change url in the finder script and remove them in this PR itself

**Comment by susmitpy** [comment]
@dchigarev 
I have updated the pull request to fix the broken series apis as well

**Review by devin-petersohn — APPROVED** [review]
@susmitpy LGTM, thanks for the contribution!

**Pull request merged**
