### PR TITLE
FIX-#3186: disable OmniSci' watchdog by default

### LINKED ISSUE #3186: Disable OmniSci' watchdog by default
In cases when watchdog raises an exception we can't do better than default to pandas, which anyway gives a worse performance in comparison with OmniSci implementation (even when watchdog consider this operation as "too slow")

### PR DESCRIPTION
**Pull request by dchigarev**
Signed-off-by: Dmitry Chigarev <dmitry.chigarev@intel.com>

## What do these changes do?

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #3186 
- [x] tests passing
- [x] module layout described at `docs/developer/architecture.rst` is up-to-date

### CODE REVIEW

**Review by vnlitvinov — COMMENTED** [review]
Changes themselves are fine, but I would like to understand the reasons and the implications of disabling the watchdog - why are we stopping it, what it was doing?

**Comment by Garra1980** [comment]
@ienkovich is the best person I think ;)

**Comment by ienkovich** [comment]
@vnlitvinov The watchdog is used to prevent too heavy queries execution. There are multiple limits applied when the watchdog is enabled. E.g. for group-by operation, we have a limit of 130M resulting groups, for sort the limit is 1M rows, etc. Sometimes these limits are too restrictive. E.g. we have to disable them to run NYC Taxi queries on a full dataset.

**Review by vnlitvinov — APPROVED** [review]
I'm satisfied with the explanation, hence LGTM.

Adding some explanations for all configuration options _somewhere_ would be awesome, though... however I guess the docs should be defined somewhere on the OmniSci side.

**Review by ienkovich — APPROVED** [review]

**Review by YarShev — APPROVED** [review]

**Pull request merged**
