### PR TITLE
Fix for bug #1588

### LINKED ISSUE #1588: Assignment of ndarray of single element ndarrays should convert data to column if these single elements
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Ubuntu 20.04

- **Modin version** (`modin.__version__`):

0.7.3+116.g568e9c6.dirty

- **Python version**:

Python 3.8.2

- **Code we can use to reproduce**:

```python
import modin.pandas as pd

df1 = pd.DataFrame({"data": [2, 3, 4, 5]})
df2 = pd.DataFrame({"col1": [11, 21, 31, 41], "col2": [12, 22, 32, 42]})
values = df1[['data']].values
print(type(values))
print(type(values[0]))
print(values)
df2['data'] = values
print(df2)
s1 = df2['data'].unique()
print(s1)
```

### Describe the problem

Running above code on Pandas shows that assignment of 2-dimensional array to a dataframe column unwraps its elements and column consists of numbers while on Modin column consists of ndarrays. This leads to unability to run `unique` or probably other dataframe functions on this column.

### PR DESCRIPTION
**Pull request by gshimansky**
## What do these changes do?

- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #1588 
- [x] tests added and passing

### CODE REVIEW

**Comment by anmyachev** [comment]
test on windows failed

**Comment by anmyachev** [comment]
Fyi

This code block works on windows.

```python
if __name__ == '__main__':
    import pandas as pd
    import numpy as np

    df2 = pd.DataFrame({"col1": [11, 21, 31, 41], "col2": [12, 22, 32, 42]})
    values = np.array([[1], [2], [3], [4]])
    print(type(values))
    print(type(values[0]))
    print(values)
    df2['data'] = values
    print(df2)
    s1 = df2['data'].unique()
    print(s1)
```

Output:
```shell
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[[1]
 [2]
 [3]
 [4]]
   col1  col2  data
0    11    12     1
1    21    22     2
2    31    32     3
3    41    42     4
[1 2 3 4]

```

**Comment by gshimansky** [comment]
No I am getting the same exception on windows. Which version of python do you use?

**Comment by anmyachev** [comment]
Python 3.8.1

Possibly  I took a wrong reproducer.(because there is no modin in it) https://github.com/modin-project/modin/issues/1588#issuecomment-643461490

**Comment by gshimansky** [comment]
Last time I checked there was no numpy binary for Windows python 3.8, therefore I had to install version 3.7.7 on Windows. What I see in the tests is that tests fail on Windows version 3.6 which I don't have at the moment.

**Comment by gshimansky** [comment]
Ok apparently on python 3.6 conversion of 2-dimensional array `value = value.copy().T[0]` converts it from `numpy.int32` to `numpy.int64` in Modin. This doesn't happen on later version of Python, so I am thinking of excluding this test for Python 3.6.

**Pull request merged**
