### PR TITLE
FIX-#1898: Support DataFrame.__setitem__ with boolean mask.

### LINKED ISSUE #1898: Version of __setitem__ that doesn't fall back to Pandas, where key is DataFrame or 2-D array
This covers one of items in #1063.

Turns out this doesn't actually fall back to Pandas, this just fails with exception, so really this is a bug.

### PR DESCRIPTION
**Pull request by itamarst**
Signed-off-by: Itamar Turner-Trauring <itamar@itamarst.org>

## What do these changes do?

Make `df[df > 2] = 3` work (previously it did not).

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #1898
- [x] tests added and passing

### CODE REVIEW

**Comment by itamarst** [comment]
Will look at failing tests.

**Comment by itamarst** [comment]
Could someone kick tests off again? Spurious failure due to network problem, looks like.

**Comment by amyskov** [comment]
> Could someone kick tests off again? Spurious failure due to network problem, looks like.

@itamarst i have restarted CI on your PR, but it doesn't solved the problem. I will try to fix this issue with CI.

**Comment by itamarst** [comment]
The `codecov/project` report is garbage :cry:

**Comment by devin-petersohn** [comment]
Codecov has given some problems before, but it is helpful when it works 😄 .

**Pull request merged**
