### PR TITLE
FIX-#4566: Pin Ray < 1.13.0 to avoid deserialization race condition.

### LINKED ISSUE #4566: BUG: We need to pin ray < 1.13.0 until we fix deserialization race condition bug #4564.
Installing modin on any system may cause serialization race conditions like in #4564.

### PR DESCRIPTION
**Pull request by mvashishtha**
Signed-off-by: mvashishtha <mahesh@ponder.io>

## What do these changes do?

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
- [x] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] signed commit with `git commit -s` 
- [x] Resolves #4566
- [x] tests added and passing
- [x] module layout described at `docs/development/architecture.rst` is up-to-date 
- [x] added (Issue Number: PR title (PR Number)) and github username to release notes for next major release

### CODE REVIEW

**Review by vnlitvinov — APPROVED** [review]
LGTM!

**Review by YarShev — COMMENTED** [review]
Should we also add a condition on the upper ray bound here?
https://github.com/modin-project/modin/blob/ba2b6ea47d81575e41af6c92ba4c2c3f8bcf54e2/modin/config/envvars.py#L94

**Comment by mvashishtha** [comment]
> Should we also add a condition on the upper ray bound here?
> 
> https://github.com/modin-project/modin/blob/ba2b6ea47d81575e41af6c92ba4c2c3f8bcf54e2/modin/config/envvars.py#L94

@YarShev yes, done.

**Comment by RehanSD** [comment]
Is this superseded by #4568 ?

**Review by devin-petersohn — COMMENTED** [review]
@mvashishtha doc build is failing because changes here are not compatible with `docs/requirements-doc.txt`. For some reason that is installing from the github.

**Comment by devin-petersohn** [comment]
This probably needs to change: https://github.com/modin-project/modin/blob/d5ff94ea75b73e8b928bda1ec6b0363d5125207a/docs/requirements-doc.txt#L12

**Comment by devin-petersohn** [comment]
@mvashishtha will you delete that line and see if that fixes it?

**Comment by mvashishtha** [comment]
> @mvashishtha will you delete that line and see if that fixes it?

@devin-petersohn that didn't work either. "Build docs" gives `No module named 'ray'` as [here](https://github.com/modin-project/modin/runs/6864210272?check_suite_focus=true). It doesn't look like I can `pip install ../.[all]` either. I'm trying to pin ray within the doc requirements.

**Review by devin-petersohn — APPROVED** [review]

**Pull request merged**
