### PR TITLE
REFACTOR-#3885: Move PandasDataframePartitionManager.concatenate to a utils

### LINKED ISSUE #3885: Move PandasDataframePartitionManager.concatenate to a utils
After the refactor and the clean abstractions, there are some leaks that weren't taken care of then. This one needs to be moved to a utils, it has nothing to do with partition management.

https://github.com/modin-project/modin/blob/67013f935861187c784415d4265a5b437dba5690/modin/core/dataframe/pandas/partitioning/partition_manager.py#L603-L627

### PR DESCRIPTION
**Pull request by naren-ponder**
Signed-off-by: Naren Krishna <naren@ponder.io>

## What do these changes do?

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [x] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] signed commit with `git commit -s` 
- [x] Resolves #3885  
- [x] tests added and passing
- [x] module layout described at `docs/developer/architecture.rst` is up-to-date

### CODE REVIEW

**Review by devin-petersohn — APPROVED** [review]
LGTM, @YarShev @dchigarev do you agree with these changes?

**Comment by YarShev** [comment]
I wonder if general.py would be a better name for the file like we have general stuff in modin.pandas.general.py?

@naren-ponder, please do not forget linking an issue in PRs description in future (I did it).

**Review by dchigarev — APPROVED** [review]
LGTM!

I'm fine with the new file being named `utils.py`, for me, `general.py` seems like a set of general methods for Modin dataframe objects, when the `concatenate` is literally an utility function to do a certain thing on pandas DataFrames inside partition manager.

**Comment by YarShev** [comment]
> LGTM!
> 
> I'm fine with the new file being named `utils.py`, for me, `general.py` seems like a set of general methods for Modin dataframe objects, when the `concatenate` is literally an utility function to do a certain thing on pandas DataFrames inside partition manager.

That makes sense

**Review by YarShev — APPROVED** [review]
LGTM

**Pull request merged**
