### PR TITLE
FIX-#2747: forward Modin categories to OmniSci

### LINKED ISSUE #2747: Map modin category type to arrow dictionary type in omnisci backend
As omnisci finally supports arrow 2.0 we could explicitly map modin's category type to arrow's dictionary type. 
This would allow us to distinguish those types in FSI.

### PR DESCRIPTION
**Pull request by dchigarev**
Signed-off-by: Dmitry Chigarev <dmitry.chigarev@intel.com>

## What do these changes do?

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [ ] passes `flake8 modin`
- [ ] passes `black --check modin`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #2747 
- [ ] tests added and passing

OmniSci branch with Arrow 2.0 and enabled support for dictionary encoding: https://github.com/dchigarev/omniscidb/tree/modin_cats

### CODE REVIEW

**Comment by dchigarev** [comment]
@modin-project/modin-omnisci 
Modin categories are now forwarded to OmniSci like arrow dictionaries, however it revealed some problems with importing arrow tables to OmniSci:
1. We can't import dictionaries, which value type is not `string`, to bypass that, we can cast non-string-categories columns to string-categories. But since we have to do it in pandas (before the creation of arrow table) it would be a really expensive operation.
2. It seems that OmniSci is having trouble when trying to import dictionaries which `index_type` is `int8` (`pa.Table.from_pandas` sets `int8` as a default type for `index_type` in a dictionary, look at the reproducer below). It's unclear to me where it should be fixed: either on OmniSci side or we have to explicitly pass schemas with the proper index type to `pa.Table.from_pandas`.

<details><summary>Reproducer</summary>

```python
import pyarrow as pa
import pandas
import sys

prev = sys.getdlopenflags()
sys.setdlopenflags(1 | 256)  # RTLD_LAZY+RTLD_GLOBAL

from dbe import PyDbEngine


pd_df = pandas.DataFrame({"col1": ["1", "2", "3"], "col2": [3, 4, 5]})
pd_df = pd_df.astype({"col1": "category"})

at_default_schema = pa.Table.from_pandas(pd_df)
assert at_default_schema.schema[0].type == pa.dictionary(
    index_type=pa.int8(), value_type=pa.string()
)

at_custom_schema = pa.Table.from_pandas(
    pd_df,
    schema=pa.schema(
        {
            # The only difference here from the default schema, is that 'index_type' is 'int32' instead of 'int8'
            "col1": pa.dictionary(index_type=pa.int32(), value_type=pa.string()),
            "col2": pa.int64(),
        }
    ),
)

server = PyDbEngine()

server.importArrowTable("test_name1", at_custom_schema)
print(f"Table with custom schema was just imported: {server.get_tables()}\n\n")

server.importArrowTable("test_name2", at_default_schema)  # SegFault
print(f"Table with the default schema was just imported: {server.get_tables()}\n\n")

```

</details>

**Comment by ienkovich** [comment]
> 1. We can't import dictionaries, which value type is not `string`, to bypass that, we can cast non-string-categories columns to string-categories. But since we have to do it in pandas (before the creation of arrow table) it would be a really expensive operation.

There are types that cannot be processed in OmniSci. We already detect such types and mark dataframe as non-supported in OmniSci to default to Pandas for it. I think non-string-based category is such a case.

> 2. It seems that OmniSci is having trouble when trying to import dictionaries which `index_type` is `int8` (`pa.Table.from_pandas` sets `int8` as a default type for `index_type` in a dictionary, look at the reproducer below). It's unclear to me where it should be fixed: either on OmniSci side or we have to explicitly pass schemas with the proper index type to `pa.Table.from_pandas`.

I believe this should be fixed in OmniSci, it can cast index type if needed.

**Comment by YarShev** [comment]
@dchigarev, what is the status here?

**Comment by dchigarev** [comment]
> what is the status here?

It's blocked by changes in OmniSci, that still haven't merged.

**Comment by YarShev** [comment]
What is the plan for adding/fixing that in OmniSci?

**Comment by Garra1980** [comment]
No exact plans now, we may define them later for engine that will eventually substitute Omnisci

**Comment by dchigarev** [comment]
closing as outdated

**Pull request closed without merging**
