### PR TITLE
FIX-#5208: pin ray version under 2.1.0

### PR DESCRIPTION
**Pull request by dchigarev**
Signed-off-by: Dmitry Chigarev <dmitry.chigarev@intel.com>

## What do these changes do?

The PR limits Ray version under 2.1.0 until we figure out the root cause of the #5208

- [x] first commit message and PR title follow format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
  > **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your last commit for the CI job that checks the PR title to pick up the new PR title.
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #? 
- [ ] tests added and passing
- [ ] module layout described at `docs/development/architecture.rst` is up-to-date

### CODE REVIEW

**Review by mvashishtha — DISMISSED** [review]

**Review by pyrito — COMMENTED** [review]
I think we need to add the restriction to a couple more files right? 
```
environment-dev.yml
requirements/requirements-py36.txt
requirements/environment-py36.yml
docs/requirements-doc.txt
requirements-dev.txt
setup.py
```

**Review by mvashishtha — APPROVED** [review]

**Comment by dchigarev** [comment]
However, we still won't get a green CI because of mypy (#5206) 😄

**Comment by dchigarev** [comment]
Maybe we should merge #5209 first as it fails on much fewer jobs?

**Review by mvashishtha — APPROVED** [review]

**Comment by dchigarev** [comment]
Rebased on master to be up-to-date with #5207 and hopefully get a green ci.

**Review by pyrito — APPROVED** [review]

**Comment by dchigarev** [comment]
CI is green, ready to merge

**Pull request merged**
