### PR TITLE
Try commits for Release 0.23.2

### PR DESCRIPTION
**Pull request by anmyachev**
## What do these changes do?

- [x] first commit message and PR title follow format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
  > **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your last commit for the CI job that checks the PR title to pick up the new PR title.
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #? 
- [ ] tests added and passing
- [ ] module layout described at `docs/development/architecture.rst` is up-to-date

### CODE REVIEW

**Comment by anmyachev** [comment]
@modin-project/modin-core please take a look at the commits I want to include in version 0.23.2. The main goal is to port the fixes to a version of Modin that still supports Python 3.8.

**Comment by sfc-gh-dpetersohn** [comment]
@anmyachev I think it looks good, you just cherry-picked the commits, correct? We can release this as a backport, but typically the naming convention we have used is `0.23.1.post0` to indicate that it is not the most recent release (despite having the most recent release date).

**Comment by anmyachev** [comment]
> @anmyachev I think it looks good, you just cherry-picked the commits, correct? We can release this as a backport, but typically the naming convention we have used is `0.23.1.post0` to indicate that it is not the most recent release (despite having the most recent release date).

Yes, just cherry-picked. Although I also had to resolve conflicts for some commits.

**Review by Garra1980 — APPROVED** [review]

**Comment by anmyachev** [comment]
Blocked by #6673

**Pull request closed without merging**
