### PR TITLE
Remove broken links from dataframe supported apis Closes #3922

### LINKED ISSUE #3922: Broken links in "Supported APIs" table
Some links to the pandas documentation are broken in the [Supported APIs page](https://modin.readthedocs.io/en/latest/supported_apis/dataframe_supported.html) and need to be updated (e.g., `as_blocks`, `as_matrix`, etc.)

### PR DESCRIPTION
**Pull request by susmitpy**
## What do these changes do?
Remove the following broken links from dataframe supported apis:
('as_blocks', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.as_blocks.html#pandas.DataFrame.as_blocks')
('as_matrix', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.as_matrix.html#pandas.DataFrame.as_matrix')
('blocks', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.blocks.html#pandas.DataFrame.blocks')
('clip_lower', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.clip_lower.html#pandas.DataFrame.clip_lower')
('clip_upper', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.clip_upper.html#pandas.DataFrame.clip_upper')
('from_items', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.from_items.html#pandas.DataFrame.from_items')
('ftypes', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.ftypes.html#pandas.DataFrame.ftypes')
('to_dense', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_dense.html#pandas.DataFrame.to_dense')
('to_msgpack', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_msgpack.html#pandas.DataFrame.to_msgpack')
('to_sparse', 'https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_sparse.html#pandas.DataFrame.to_sparse')

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] signed commit with `git commit -s` 
- [x] Resolves #3922 
- [ ] tests added and passing
- [ ] module layout described at `docs/developer/architecture.rst` is up-to-date

### CODE REVIEW

**Comment by mvashishtha** [comment]
@susmitpy thank you for the changes! The changes look fine. Could you please:

- `git commit --amend` your first commit so that it follows the format [here](https://modin.readthedocs.io/en/latest/developer/contributing.html#commit-message-formatting)
- Change the first line of the pull request so it matches the new first line of the commit message

**Comment by susmitpy** [comment]
@mvashishtha After amending commits and doing a merge due to changes, one commit became 3 commits. 
So I have created another pull request: #3968 Can you close this pull request ?

**Comment by mvashishtha** [comment]
@susmitpy now that you have #3968, we'll continue the review there. However, for future reference, it's okay if a pull request has multiple comments. We would squash the commits into a single commit before merging.

**Comment by susmitpy** [comment]
Sure !

**Pull request closed without merging**
