### PR TITLE
REFACTOR-#3684: remove compression check in '_read_csv_check_support'

### LINKED ISSUE #3684: REFACTOR: remove compression check from ` _read_csv_check_support` function
This [check](https://github.com/modin-project/modin/blob/6178a5764489e05aa85b4bf47a6fecac2c89c53e/modin/core/io/text/csv_dispatcher.py#L205) is used to identify situations where Modin does not support any compression format in order to use the pandas code in these cases. However we can rely on `infer_compression` [function](https://github.com/modin-project/modin/blob/6178a5764489e05aa85b4bf47a6fecac2c89c53e/modin/core/io/text/csv_dispatcher.py#L75) from the pandas(called before checks), which will throw an exception if the compression algorithm is not supported.

### PR DESCRIPTION
**Pull request by anmyachev**
Signed-off-by: Anatoly Myachev <anatoly.myachev@intel.com>

## What do these changes do?

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] signed commit with `git commit -s` 
- [x] Resolves #3684 
- [ ] tests added and passing
- [ ] module layout described at `docs/developer/architecture.rst` is up-to-date

### CODE REVIEW

**Review by vnlitvinov — COMMENTED** [review]
What if we use pyarrow to read (or some other library) which might be supporting _less_ potential compressions than pandas?..

**Comment by anmyachev** [comment]
> What if we use pyarrow to read (or some other library) which might be supporting _less_ potential compressions than pandas?..

Modin deals with the issue of opening archives itself(we use `fsspec` for this), so `pyarrow` or some another library will work with unpacked data.

**Review by vnlitvinov — APPROVED** [review]
LGTM

**Comment by vnlitvinov** [comment]
It just came to me - what about OmniSci?

**Comment by anmyachev** [comment]
> It just came to me - what about OmniSci?

OmniSci has it' own version of `_read_csv_check_support` function: https://github.com/modin-project/modin/blob/9498b927ab0e1fd31b20ebc3b79dc41dff00fae0/modin/experimental/core/execution/native/implementations/omnisci_on_native/io/io.py#L409

**Pull request merged**
