### PR TITLE
TEST-#3708: use 'latest' tag for 'rayproject/ray' base Ray image

### LINKED ISSUE #3708: Update base Ray image in teamcity ci dockerfile
Ray image should be updated in this line.https://github.com/modin-project/modin/blob/8d67cd3a467d1eb2262898f6f5e2cf159c27d7b0/ci/teamcity/Dockerfile.teamcity-ci#L9

### PR DESCRIPTION
**Pull request by anmyachev**
Signed-off-by: Anatoly Myachev <anatoly.myachev@intel.com>

## What do these changes do?

Updates the image in order not to use the outdated one.

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [x] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] signed commit with `git commit -s` 
- [x] Resolves #3708 
- [x] tests added and passing
- [x] module layout described at `docs/developer/architecture.rst` is up-to-date

### CODE REVIEW

**Review by YarShev — DISMISSED** [review]
LGTM

**Comment by YarShev** [comment]
@anmyachev , what is the reason of TeamCity tests fail?

**Comment by vnlitvinov** [comment]
> @anmyachev , what is the reason of TeamCity tests fail?

I've re-run the builds, we'll see how it goes.

**Comment by anmyachev** [comment]
> @anmyachev , what is the reason of TeamCity tests fail?

In Ray image, the default user was changed - now it is not a `root`, but `ray`.

**Review by vnlitvinov — COMMENTED** [review]
LGTM when CI passes.

**Comment by vnlitvinov** [comment]
> /home/ray/anaconda3/bin/python: No module named pytest
> /home/ray/anaconda3/bin/python: No module named pytest

This is the quote from TeamCity... @anmyachev something's broken.

**Comment by anmyachev** [comment]
@YarShev @vnlitvinov ready for review

**Review by YarShev — APPROVED** [review]

**Review by vnlitvinov — APPROVED** [review]
LGTM

**Pull request merged**
