### PR TITLE
REFACTOR-#4708: Delete combine dtypes.

### LINKED ISSUE #4708: REFACTOR: Delete PandasDataFrame.combine_dtypes
### System information
- **Modin version** (`modin.__version__`): 98d3dbf70bb19571e0864ccbeccc14d5c61a5dad

The function is defined [here](https://github.com/modin-project/modin/blob/81648e711f7525d87dbc58f53e67a2fd22650ae7/modin/core/dataframe/pandas/dataframe/dataframe.py#L965) and overridden in two subclasses, but we never use it.

### PR DESCRIPTION
**Pull request by mvashishtha**
## What do these changes do?

REFACTOR-#4708: Delete combine dtypes.

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
- [x] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] signed commit with `git commit -s` 
- [x] Resolves #4708
- [x] tests added and passing
- [x] module layout described at `docs/development/architecture.rst` is up-to-date 
- [x] added (Issue Number: PR title (PR Number)) and github username to release notes for next major release

### CODE REVIEW

**Review by pyrito — COMMENTED** [review]
Seconding @jeffreykennethli 's point, I wonder if these functions were intended to be used in the future. `git blame` shows me that @devin-petersohn was the author of the function in `core/dataframe` and @prutskov made some edits around here. Do either of you two have any comments about this?

**Comment by mvashishtha** [comment]
@pyrito @jeffreykennethli this function has not been used since #721 at `54b28cd64c2742527588db71a496c013daec12aa`. Even in the commit that introduced it, it was not used for anything. I double checked by checking out Modin at that commit and running `grep -r . -e "combine_dtypes" --include=*.py`. The only matches were the function definitions. I think we can delete it without checking with @devin-petersohn .

**Review by pyrito — APPROVED** [review]

**Review by vnlitvinov — APPROVED** [review]
LGTM!

**Review by RehanSD — APPROVED** [review]
LGTM!

**Pull request merged**
