### PR TITLE
FIX-#2522: Added optional default parameter to pop method

### LINKED ISSUE #2522: conftest.PatchedEnv doesn't implement pop() quite right, leading to TypeErrors in some edge cases
### System information
- Fedora 33
- **Modin version** (`modin.__version__`): 0.8.2.1+40.g26c21e9
- **Python version**: 3.8

### Describe the problem
In modin/conftest.py, `PatchedEnv.pop` doesn't support the optional second argument that normal dictionaries do, resulting in:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/itamarst/Devel/modin/venv/lib64/python3.8/site-packages/_pytest/main.py", line 257, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/itamarst/Devel/modin/venv/lib64/python3.8/site-packages/_pytest/main.py", line 313, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/itamarst/Devel/modin/venv/lib64/python3.8/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/itamarst/Devel/modin/venv/lib64/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/itamarst/Devel/modin/venv/lib64/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/home/itamarst/Devel/modin/venv/lib64/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/itamarst/Devel/modin/venv/lib64/python3.8/site-packages/pytest_cov/plugin.py", line 262, in pytest_runtestloop
INTERNALERROR>     yield
INTERNALERROR>   File "/home/itamarst/Devel/modin/venv/lib64/python3.8/site-packages/pytest_cov/engine.py", line 44, in ensure_topdir_wrapper
INTERNALERROR>     return meth(self, *args, **kwargs)
INTERNALERROR>   File "/home/itamarst/Devel/modin/venv/lib64/python3.8/site-packages/pytest_cov/engine.py", line 228, in finish
INTERNALERROR>     self.unset_env()
INTERNALERROR>   File "/home/itamarst/Devel/modin/venv/lib64/python3.8/site-packages/pytest_cov/engine.py", line 109, in unset_env
INTERNALERROR>     os.environ.pop('COV_CORE_SOURCE', None)
INTERNALERROR> TypeError: pop() takes 2 positional arguments but 3 were given
```

With a normal Python dictionary, `os.enviorn.pop("WHATEVER", None)` returns `None` if `WHATEVER` isn't set.

### PR DESCRIPTION
**Pull request by alphavector**
Signed-off-by: Marat Idrisov <idrisov.mt@yandex.ru>

## What do these changes do?

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #2522 
- [ ] tests added and passing _Do we need tests?_
___
A question may arise: Why is the default value not `None` but `object()`?
`os.environ` returns an object of the class `os._Environ`. `_Environ` is inherited from `_collections_abc.MutableMapping`. The [MutableMapping.pop](https://github.com/python/cpython/blob/3.8/Lib/_collections_abc.py#L790) method has `object()` as default value.

### CODE REVIEW

**Comment by devin-petersohn** [comment]
Restarting CI, one of the tests timed out

**Comment by alphavector** [comment]
For some reason the `codecov/project` task fails
`63.55% (-19.31%) compared to 057eb61` - why is the comparison not with master, but with 057eb61?

**Comment by alphavector** [comment]
My mistake, 057eb61 was a master at the time of the tests

**Comment by devin-petersohn** [comment]
It is fine, these change are not conflicting with changes in the master. 

Codecov is broken for PRs. We are planning to fix it after this release.

**Comment by devin-petersohn** [comment]
@alphavector CI timed out again. Could you rebase on the current master? I didn't think it was necessary, but there may be some changes for CI to complete.

**Comment by alphavector** [comment]
I think I broke it....

**Comment by devin-petersohn** [comment]
That did it. Thanks @alphavector

**Pull request merged**
