### PR TITLE
FIX-#6578: ignore `FutureWarning`s in pandas kernel which used for defaulting to pandas

### LINKED ISSUE #6578: `align` func shows `FutureWarning`s in cases where they are not needed.

### PR DESCRIPTION
**Pull request by anmyachev**
## What do these changes do?

~Now there is only a basic implementation that defaults to pandas. We may not process parameters on the Modin side.~

- [x] first commit message and PR title follow format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
  > **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your last commit for the CI job that checks the PR title to pick up the new PR title.
- [x] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] signed commit with `git commit -s` 
- [x] Resolves #6578 
- [x] tests added and passing
- [x] module layout described at `docs/development/architecture.rst` is up-to-date

### CODE REVIEW

**Review by vnlitvinov — CHANGES_REQUESTED** [review]
I don't understand why we are not giving these warnings. Higher-level API should not depend on lower-level implementation details to give warnings about these, as implementation might change without notice for higher-level parts.

On the contrary, it's lower level that ought to suppress the warnings that high-level had already given, if such warnings arise in the implementation.

IMHO, this change is not solving the original problem, but rather replacing it with another one 🙃

**Comment by vnlitvinov** [comment]
> There is a high probability that we will filter out the warning that Modin does not show, that is, a situation will arise when the user does not receive a warning at all, which in my understanding is a bad decision.

Given Modin strives to be pandas drop-in replacement with whatever backend user picks, the _only_ place that should be raising warnings is the high-level API layer. These changes mean that on non-pandas backend the user will _not_ get the warnings you've removed here at all.

As for missing some warnings because Modin does not give them - this would be a bug in Modin, and relying on lower-level to give those for us is a workaround at best.

**Comment by anmyachev** [comment]
> > There is a high probability that we will filter out the warning that Modin does not show, that is, a situation will arise when the user does not receive a warning at all, which in my understanding is a bad decision.
> 
> Given Modin strives to be pandas drop-in replacement with whatever backend user picks, the _only_ place that should be raising warnings is the high-level API layer. The changes in this PR mean that on non-pandas backend the user will _not_ get the warnings you've removed here at all.
> 
> As for missing some warnings because Modin does not give them - this would be a bug in Modin, and relying on lower-level to give those for us is a workaround at best. So the proper solution is to silence _all_ pandas warnings from the query compiler layer and explicitly raise them ourselves at API layer, IMO.

I agree, I also considered these changes as a workaround, given that we need to release it soon. However, I still changed my approach towards what you are talking about. Now all these `FutureWarning`s are filtered in the pandas kernel for operations that are defaulted by the pandas (it's enough for `align` op). I propose to correct all other places and other types of warnings separately.

**Comment by anmyachev** [comment]
Blocked on #6595

**Comment by anmyachev** [comment]
Will be fixed in #6595

**Pull request closed without merging**
