### PR TITLE
TEST-#1985: optimize common test dataset

### LINKED ISSUE #1985: Optimize common test dataset

### PR DESCRIPTION
**Pull request by anmyachev**
Signed-off-by: Anatoly Myachev <anatoly.myachev@intel.com>

## What do these changes do?

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #1985 
- [x] tests added and passing

### CODE REVIEW

**Comment by dchigarev** [comment]
@anmyachev I don't think it's a good idea to combine `float` and `nan` into a single dataset. It's a common case when something doesn't work with `nan` values and that tests marked as `xfail`. But in that case, we still want to run that test with `float` data.

However, it's just my opinion, let's wait for some others 
@devin-petersohn @gshimansky

**Comment by anmyachev** [comment]
> @anmyachev I don't think it's a good idea to combine `float` and `nan` into a single dataset. It's a common case when something doesn't work with `nan` values and that tests marked as `xfail`. But in that case, we still want to run that test with `float` data.
> 
> However, it's just my opinion, let's wait for some others
> @devin-petersohn @gshimansky

At the moment, "float_with_nan" dataset does not cause problems anywhere. If in the future there are any problems with the processing of this value, then you can simply use `dropna` method before check.

By the way, if we remember that `skipna` occurs very often in Pandas api, then we can conclude that the situation when `nan` value is encountered in the dataset occurs quite often.

**Review by dchigarev — APPROVED** [review]
thanks @anmyachev!
lgtm

**Comment by anmyachev** [comment]
@dchigarev thanks for review!

**Comment by anmyachev** [comment]
part of #2008

**Comment by devin-petersohn** [comment]
Thanks @anmyachev this is very nice!

**Pull request merged**
