### PR TITLE
FIX-#3387: Fix `read_csv` with `skiprows` parameter

### LINKED ISSUE #3387: `read_csv` fails if `skiprows` values are out of `index` boundaries
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Any
- **Modin version**: dd91a78ad3f4b8e3e569215e9c8e540ad099d4a8
- **Python version**: 3.8.10
- **Code we can use to reproduce**:
```
import os
import modin.pandas as pd
from modin.config import NPartitions

NPartitions.put(4)

test_filename = "test.csv"
data = """col1,col2
1,2
3,4
"""

skiprows = [x for x in range(100) if x % 2 == 0]

try :
    with open(test_filename, "w") as f:
        f.write(data)
    
    df = pd.read_csv(test_filename, skiprows=skiprows)

finally:
    os.remove(test_filename)
```

### Source code / logs

```
    df = pd.read_csv(test_filename, skiprows=skiprows)
  File "/modin/modin/pandas/io.py", line 131, in read_csv
    return _read(**kwargs)
  File "/modin/modin/pandas/io.py", line 59, in _read
    pd_obj = FactoryDispatcher.read_csv(**kwargs)
  File "/modin/modin/data_management/factories/dispatcher.py", line 172, in read_csv
    return cls.__factory._read_csv(**kwargs)
  File "/modin/modin/data_management/factories/factories.py", line 206, in _read_csv
    return cls.io_cls.read_csv(**kwargs)
  File "/modin/modin/engines/base/io/file_dispatcher.py", line 68, in read
    query_compiler = cls._read(*args, **kwargs)
  File "/modin/modin/engines/base/io/text/csv_dispatcher.py", line 155, in _read
    new_query_compiler = cls._get_new_qc(
  File "/modin/modin/engines/base/io/text/csv_dispatcher.py", line 334, in _get_new_qc
    index=index_range.delete(skiprows_md - header_size)
  File "/miniconda3/envs/modin_new/lib/python3.8/site-packages/pandas/core/indexes/range.py", line 432, in delete
    return self._int64index.delete(loc)
  File "/miniconda3/envs/modin_new/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5954, in delete
    res_values = np.delete(self._data, loc)
  File "<__array_function__ internals>", line 5, in delete
  File "/miniconda3/envs/modin_new/lib/python3.8/site-packages/numpy/lib/function_base.py", line 4552, in delete
    keep[obj,] = False
IndexError: index 3 is out of bounds for axis 0 with size 2
```

### PR DESCRIPTION
**Pull request by amyskov**
Signed-off-by: Alexander Myskov <alexander.myskov@intel.com>

## What do these changes do?

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #3387 
- [x] tests added and passing
- [x] module layout described at `docs/developer/architecture.rst` is up-to-date

### CODE REVIEW

**Comment by amyskov** [comment]
Hi @modin-project/modin-core PR is ready for review.

**Comment by YarShev** [comment]
The changes do apparently not resolve the issue.

The example from the issue.
```python
import os
import modin.pandas as pd
from modin.config import NPartitions

NPartitions.put(4)

test_filename = "test.csv"
data = """col1,col2
1,2
3,4
"""

skiprows = [x for x in range(100) if x % 2 == 0]

try :
    with open(test_filename, "w") as f:
        f.write(data)
    
    df = pd.read_csv(test_filename, skiprows=skiprows)

finally:
    os.remove(test_filename)

print(df)
   1  2
0  1  2
# but if I change `import modin.pandas as pd` to `import pandas as pd`, I get this output
Empty DataFrame
Columns: [1, 2]
Index: []
```

**Review by devin-petersohn — COMMENTED** [review]
Does this share some changes with #3419?

**Comment by amyskov** [comment]
> Does this share some changes with #3419?

Changes of these two PRs are close, but they do slightly different things. #3419 is responsible for cases when `skiprows` and `header` values have intersections and this PR handles the cases when `skiprows` contains values, which are outside of resulting query compiler `index` boundaries. The plan is to fix #3419 first and then return to this one.

**Comment by devin-petersohn** [comment]
>The plan is to fix #3419 first and then return to this one.

Sounds good.

**Pull request closed without merging**
