### PR TITLE
FIX-#3161: Update pandas to 1.2.5

### LINKED ISSUE #3161: Update pandas to 1.2.5

### PR DESCRIPTION
**Pull request by YarShev**
Signed-off-by: Igoshev, Yaroslav <yaroslav.igoshev@intel.com>

## What do these changes do?

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #3161  
- [ ] tests added and passing
- [x] module layout described at `docs/developer/architecture.rst` is up-to-date

### CODE REVIEW

**Review by devin-petersohn — COMMENTED** [review]
I wonder why pydocstyle is giving this error now:

```
AttributeError: module 'modin.engines.base.frame' has no attribute 'partition'
```

**Comment by YarShev** [comment]
> I wonder why pydocstyle is giving this error now:
> 
> ```
> AttributeError: module 'modin.engines.base.frame' has no attribute 'partition'
> ```

@devin-petersohn , my guess is there were some inconsistencies between packages.

**Review by devin-petersohn — DISMISSED** [review]
The changes to `prod` and `sum` make me very happy. I was not a fan of `squeeze_self`.

LGTM, thanks!

**Comment by devin-petersohn** [comment]
@YarShev TeamCity is failing for Ray, would you take a look? Otherwise looks good!

**Comment by YarShev** [comment]
@devin-petersohn , something went wrong with Ray. I restarted CI and tests passed.

**Review by devin-petersohn — APPROVED** [review]

**Pull request merged**
