### PR TITLE
Progress bar

### LINKED ISSUE #629: Modin progress bar
mdf['title'].apply(func)
modin can add a modin-process-bar

---
image

### PR DESCRIPTION
**Pull request by noah-kuo**
## What do these changes do?

- Resolves #629 
- Adds a progress bar when building a dataframe or performing computation

## Related issue number

- [ ] passes `flake8 modin`
- [ ] passes `black --check modin`
- [ ] tests added and passing

### CODE REVIEW

**Comment by icaropires** [comment]
Is this still going to be merged?

**Comment by devin-petersohn** [comment]
@icaropires Yes, we will pick this back up. There are some other bugfixes/high priority features to get in first but it will be merged.

**Comment by icaropires** [comment]
> @icaropires Yes, we will pick this back up. There are some other bugfixes/high priority features to get in first but it will be merged.

Great! Thanks for the information @devin-petersohn

**Comment by devin-petersohn** [comment]
Closing in favor of #1589.

**Pull request closed without merging**
