### PR TITLE
REFACTOR-#2656: Create base Modin Dataframe, and begin implementing Algebra

### PR DESCRIPTION
**Pull request by RehanSD**
Signed-off-by: Rehan Durrani <rehan@ponder.io>

## What do these changes do?
Preceded by #2744.

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #? 
- [ ] tests added and passing
- [ ] module layout described at `docs/developer/architecture.rst` is up-to-date

### CODE REVIEW

**Comment by YarShev** [comment]
@RehanSD , what is the difference between this PR and #2744?

**Comment by RehanSD** [comment]
@YarShev PR #2744 has become too stale, so @devin-petersohn and I decided it would be better to start a new PR branched off of master with the same changes without having to worry about the myriad merge conflicts in #2744, especially since some of those changes have already been merged since #2744 was started.

**Comment by YarShev** [comment]
@RehanSD , that makes sense. Please, close #2744 then.

**Comment by RehanSD** [comment]
To tighten the scope, we decided to split this PR into two PR's - one for the code, and one for the docs. The code PR - #3717  is currently in review, while the docs PR has not been created yet.

**Pull request closed without merging**
