### PR TITLE
FEAT-#0000: use ray wait to trigger computation

### PR DESCRIPTION
**Pull request by anmyachev**
Signed-off-by: Anatoly Myachev <anatoly.myachev@intel.com>

## What do these changes do?

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [ ] passes `flake8 modin`
- [ ] passes `black --check modin`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #? 
- [ ] tests added and passing

### CODE REVIEW

**Review by devin-petersohn — COMMENTED** [review]
@anmyachev Maybe we should add a "synchronous mode" to Modin. What do you think?

**Comment by anmyachev** [comment]
> @anmyachev Maybe we should add a "synchronous mode" to Modin. What do you think?

I don't see reasons why the user would want this behavior. But on the other hand, it will be convenient for us to measure the time of different functions inside a script or notebook.

Perhaps we should try adding such a mode and see how it complicates the code.

**Comment by devin-petersohn** [comment]
I think it will mostly be useful for benchmarking, not for users.

**Comment by anmyachev** [comment]
"Synchronous mode" added in #2800

**Pull request closed without merging**
