### PR TITLE
Parity fixes

### PR DESCRIPTION
**Pull request by elonp**
A few parity fixes in series and dataframes:
1. Missing right-operators added (e.g. ```__radd__``` that allows 10+s where s is a Series)
2. Added support for callable key in ```Series.__getitem__```.
3. Fixed bug in ```df.loc[row_key]``` where ```row_key``` was used as a column key if it happened to match columns

## Related issue number

None that I could find

- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] tests added and passing

### CODE REVIEW

**Comment by devin-petersohn** [comment]
Thanks @elonp!

Since you're a return contributor, would it be possible to split this patch up into the individual components being fixed? Ideally, we would like to have one PR for one fix, that way if we need to roll back we don't have to undo a bunch of unrelated changes.

If you'd like for me to help with this, I'm happy to, just let me know!

**Comment by elonp** [comment]
Sure.
But I'm travelling with limited connectivity until the 23rd. I might find
time to do it before, but feel free to go ahead and do it yourself if you'd
like.

Thanks!

Elon

**Comment by devin-petersohn** [comment]
@elonp I cherry-picked the commits from this PR into 3 separate PRs and created 3 issues in the issue tracker to track/label the fixes.

#1084, #1086, and #1088 are the new PRs

**Comment by elonp** [comment]
Great.  Thank you.

**Comment by devin-petersohn** [comment]
Closing as this work was merged.

**Pull request closed without merging**
