### PR TITLE
TEST-#4032: Only run unit tests when code changes are made

### LINKED ISSUE #4032: Change-dependent CI/CD testing
Suggestion to modify CI/CD so that only relevant test suites are run depending on what code is changed on a per commit level. For example, if we change the documentation or any non-*.py files, it probably is not necessary to run through our main test suites, but we only need to run the docs checks. This will help reduce the overall runtime of the test suite.

### PR DESCRIPTION
**Pull request by devin-petersohn**
Resolves #4032

Signed-off-by: Devin Petersohn <devin.petersohn@gmail.com>

## What do these changes do?

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/developer/contributing.html#commit-message-formatting)
- [x] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] signed commit with `git commit -s` 
- [x] Resolves #4032 
- [x] tests ~added and~ passing
- [x] module layout described at `docs/development/architecture.rst` is up-to-date

### CODE REVIEW

**Review by YarShev — APPROVED** [review]
LGTM!

**Comment by YarShev** [comment]
Btw, what about push.yml and push-to-master.yml files?

**Comment by devin-petersohn** [comment]
>Btw, what about push.yml and push-to-master.yml files?

I thought it was ok to run push.yml and push-to-master.yml on every commit, but since many CI runs happen for every commit this will cut down some of the time spent in CI.

**Review by RehanSD — APPROVED** [review]
LGTM!

**Review by YarShev — APPROVED** [review]

**Comment by anmyachev** [comment]
What about changes in workflows itself (`.github` folder)?

What about changes in following files:
- `environment-dev.yml`
- `requirements-dev.txt`
- `setup.py`
- `setup.cfg`
- `versioneer.py`
- `scripts` folder(with code for doc checker)
- `requirements` folder that include deps for OmniSci mode
- `asv_bench` folder that include code for benchmarking

If we do not run tests for them, then this will lead to non-working merged code.

**Comment by YarShev** [comment]
@anmyachev, good catch! We should probably add them as well to paths. Would you open a PR?

**Comment by prutskov** [comment]
@modin-project/modin-core, `lint-commit` should be run on every PR, but now DOCS-related PRs aren't checked on correctness of commit messages.

**Comment by YarShev** [comment]
Yes, that should go to the list above.

**Pull request merged**
