### PR TITLE
DOCS-#6416: fix import path for spreadsheet feature

### LINKED ISSUE #6416: BUG: No module named 'modin.spreadsheet'
### Modin version checks
- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the latest released version of Modin.
- [X] I have confirmed this bug exists on the main branch of Modin. (In order to do this you can follow [this guide](https://modin.readthedocs.io/en/stable/getting_started/installation.html#installing-from-the-github-master-branch).)
### Reproducible Example
https://github.com/modin-project/modin/blob/532d66ec221cba4944f35586f5ca89ded8a91889/docs/usage_guide/advanced_usage/spreadsheets_api.rst
```python
import modin.pandas as pd
import modin.spreadsheet as mss
```
### Issue Description

Can't import modin.spreadsheet.
(Issue cross-posted here, per @pyrito's recommendation.)

### Expected Behavior

No error.

### Error Logs

See https://github.com/modin-project/modin-spreadsheet/issues/51

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 6a5416c7cbe230bcd3fb359165f1eee535d35658
python           : 3.10.11.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.22621
machine          : AMD64
processor        : Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : English_United States.1252

Modin dependencies
------------------
modin            : 0.23.0
ray              : 2.6.1
dask             : 2023.7.1
distributed      : 2023.7.1
hdk              : None

pandas dependencies
-------------------
bottleneck : None
brotli :
bs4 : 4.12.2
Cython : 0.29.35
dateutil : 2.8.2
fastparquet : None
feather : None
fsspec : 2023.6.0
gcsfs : None
html5lib : None
hypothesis : None
IPython : 8.14.0
jinja2 : 3.1.2
lxml.etree : None
matplotlib : None
numba : 0.57.0
numexpr : None
numpy : 1.24.3
odfpy : None
openpyxl : None
pandas : 2.0.3
pandas_datareader: None
pandas_gbq : None
pip : 23.1.2
psycopg2 : None
pyarrow : 12.0.1
pymysql : None
pyqt5 : None
pyreadstat : None
pytest : None
pytz : 2023.3
pyxlsb : None
qtpy : None
s3fs : None
scipy : 1.10.1
setuptools : 67.7.2
snappy : None
sphinx : None
sqlalchemy : None
tables : None
tabulate : None
tzdata : 2023.3
xarray : None
xlrd : None
xlsxwriter : None
zstandard : 0.19.0

</details>

### PR DESCRIPTION
**Pull request by anmyachev**
## What do these changes do?

- [x] first commit message and PR title follow format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
  > **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your last commit for the CI job that checks the PR title to pick up the new PR title.
- [x] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] signed commit with `git commit -s` 
- [x] Resolves #6416 
- [x] tests added and passing
- [x] module layout described at `docs/development/architecture.rst` is up-to-date

### CODE REVIEW

**Comment by anmyachev** [comment]
@mvashishtha could you make new release of `modin[spreadsheet]`? Then we can upgrade the pin in Modin to a working version.

**Review by Garra1980 — APPROVED** [review]

**Comment by mvashishtha** [comment]
@anmyachev I can make a release, but do we need a  release before merging this PR?

**Comment by anmyachev** [comment]
> @anmyachev I can make a release, but do we need a release before merging this PR?

no, firstly - new release of https://github.com/modin-project/modin-spreadsheet. Then we will update pin in modin something like:
```python
spreadsheet_deps = ["modin-spreadsheet>=0.1.3"] (instead of >=0.1.0)
```

At the end we will release Modin itself (with updated pin).

**Review by mvashishtha — APPROVED** [review]

**Comment by rootsmusic** [comment]
@anmyachev commented:
> firstly - new release of https://github.com/modin-project/modin-spreadsheet. Then we will update pin in modin

Thanks @anmyachev, I was assuming that modin-spreadsheet has been abandoned.  Open issue for a new release at https://github.com/modin-project/modin-spreadsheet/issues/48

**Comment by anmyachev** [comment]
> @anmyachev I can make a release, but do we need a release before merging this PR?

@mvashishtha what about making a release of `modin-spreadsheet`? Do you have time for that?

**Pull request merged**
