### PR TITLE
REFACTOR-#1879: Move logic for `groupby.agg` into query compiler

### LINKED ISSUE #1879: Move groupby.agg logic into query compiler
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 19.04
- **Modin installed from (source or binary)**: source
- **Modin version**: master
- **Python version**: 3.8.3
- **Exact command to reproduce**: python test.py

Test case:
```
import os

os.environ["MODIN_ENGINE"] = "ray"

import modin.pandas as pd

data = {
    "a": [1, 1, 2, 2],
    "b": [11, 21, 12, 11],
}

df = pd.DataFrame(data)
ref = df.groupby("a").agg({"b": "mean"})
print(ref)
```

In the execution log I see
```
UserWarning: `DataFrame.groupby_on_multiple_columns` defaulting to pandas implementation.
```

Previously we could process such aggregates in OmniSci back-end, now it's defaulted to pandas in front-end. That 'breaks' OmniSci backend (processing doesn't happen in OmniSci). Don't know when degradation happened. Probably some code was moved from query compiler to front-end.

### PR DESCRIPTION
**Pull request by devin-petersohn**
Signed-off-by: Devin Petersohn <devin.petersohn@gmail.com>

## What do these changes do?

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #1879 
- [x] tests ~added and~ passing

### CODE REVIEW

**Comment by ienkovich** [comment]
This one is the last blocker for #1871, could you please look at it? @devin-petersohn @YarShev

**Comment by devin-petersohn** [comment]
@ienkovich I just rebased and pushed. I believe previous test failures were do to CI infra issues.

**Comment by devin-petersohn** [comment]
@ienkovich @YarShev This is ready for review

**Comment by ienkovich** [comment]
Changes LGTM

**Comment by YarShev** [comment]
LGTM as well!

**Review by YarShev — APPROVED** [review]

**Pull request merged**
