### PR TITLE
TEST-#4821: monkeypatch `cache_readonly` to avoid errors in `doc_checker.py`

### LINKED ISSUE #4821: BUG: `scripts/doc_checker.py` throws error when using pandas `cache_readonly` decorator
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 12.2.1
- **Modin version** (`modin.__version__`): 0.15.2
- **Python version**: 3.9.12
- **Code we can use to reproduce**:
```python
from pandas.util._decorators import cache_readonly

class A:

    def __init__(self):
        self._thing = 5

    @cache_readonly
    def thing(self):
        """Return the value of thing."""
        self._thing += 5
        return self._thing
```

### Describe the problem
If we have a class like the one above, our doc_checker script seems to throw an error when trying to complete its check. You can see more information in the logs below.

### Source code / logs

<details>
<summary>Show stack trace</summary>

```
INFO:Note: NumExpr detected 10 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
Traceback (most recent call last):
  File "/Users/kvelayutham/Documents/modin/scripts/doc_checker.py", line 631, in <module>
    if not validate(args.paths, args.add_ignore, not args.disable_numpydoc):
  File "/Users/kvelayutham/Documents/modin/scripts/doc_checker.py", line 563, in validate
    if not numpydoc_validate(path):
  File "/Users/kvelayutham/Documents/modin/scripts/doc_checker.py", line 444, in numpydoc_validate
    results = list(map(validate_object, to_validate))
  File "/Users/kvelayutham/Documents/modin/scripts/doc_checker.py", line 369, in validate_object
    results = validate_modin_error(doc, results)
  File "/Users/kvelayutham/Documents/modin/scripts/doc_checker.py", line 257, in validate_modin_error
    errors += check_spelling_words(doc)
  File "/Users/kvelayutham/Documents/modin/scripts/doc_checker.py", line 188, in check_spelling_words
    for idx, line in enumerate(inspect.getsourcelines(doc.code_obj)[0]):
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/inspect.py", line 1006, in getsourcelines
    lines, lnum = findsource(object)
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/inspect.py", line 817, in findsource
    file = getsourcefile(object)
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/inspect.py", line 697, in getsourcefile
    filename = getfile(object)
  File "/Users/kvelayutham/opt/anaconda3/envs/modin/lib/python3.9/inspect.py", line 677, in getfile
    raise TypeError('module, class, method, function, traceback, frame, or '
TypeError: module, class, method, function, traceback, frame, or code object was expected, got CachedProperty
```

</details>

### PR DESCRIPTION
**Pull request by anmyachev**
Signed-off-by: Myachev <anatoly.myachev@intel.com>

## What do these changes do?

- [x] first commit message and PR title follow format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
  > **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your last commit for the CI job that checks the PR title to pick up the new PR title.
- [x] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] signed commit with `git commit -s` 
- [x] Resolves #4821 
- [ ] tests added and passing
- [x] module layout described at `docs/development/architecture.rst` is up-to-date

### CODE REVIEW

**Review by mvashishtha — APPROVED** [review]

**Comment by anmyachev** [comment]
The change actually helps as we can see in https://github.com/modin-project/modin/pull/5354.

**Comment by anmyachev** [comment]
@mvashishtha I think we can merge it right now

**Comment by anmyachev** [comment]
thanks @mvashishtha !

**Comment by vnlitvinov** [comment]
This is actually doing things in a wrong way 😞 

As it would break `help(Foo.prop)` when _not_ testing a doc but running interactively. We should have fixed the `_inherit_docstrings()` decorator to properly decorate things instead of hiding stuff under the rug.

**Comment by anmyachev** [comment]
> This is actually doing things in a wrong way 😞
> 
> As it would break `help(Foo.prop)` when _not_ testing a doc but running interactively. We should have fixed the `_inherit_docstrings()` decorator to properly decorate things instead of hiding stuff under the rug.

So this only works erroneously with `_inherit_docstrings`?

**Pull request merged**
