### PR TITLE
FIX-#2869: Fix setting NPartitions via put

### LINKED ISSUE #2869: Fix setting NPartitions via put
### Describe the problem
We need to reset `is_default` to `False` after base `put` call because we may meet `_get_default` call inside of base `put` (if `MODIN_NPARTITIONS` wasn't set) that can change `is_default` to `True`.

### Source code / logs
```python
import modin.pandas as pd
from modin.config import NPartitions
import numpy as np
NPartitions.put(1)
df = pd.DataFrame(np.arange(2 ** 10))
df._query_compiler._modin_frame._partitions.shape[0] == 1
False
```

### PR DESCRIPTION
**Pull request by YarShev**
Signed-off-by: Igoshev, Yaroslav <yaroslav.igoshev@intel.com>

## What do these changes do?

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #2869  
- [x] tests added and passing

### CODE REVIEW

**Review by devin-petersohn — APPROVED** [review]
Thanks @YarShev LGTM!

**Comment by YarShev** [comment]
@devin-petersohn , I reran the tests because io tests hung for some reason.

**Comment by devin-petersohn** [comment]
@YarShev Thank you, I could not get them to rerun.

Windows test can sometimes hang for 6 hours+. Do we have an open issue for that? It's hard to identify why it happens, sometimes it just does, but setting a lower timeout would help a lot.

**Comment by YarShev** [comment]
Yes, I see Windows tests hanging not at first time as well. We don't have an open issue for that. Probably, yes, the timeout would be good solution.

**Comment by devin-petersohn** [comment]
@YarShev tests are hanging again. I will restart once they are shut down.

**Comment by YarShev** [comment]
I have restarted the tests 😄  Will see how it goes at this time.

**Comment by YarShev** [comment]
@devin-petersohn , tests passed.

**Pull request merged**
