### PR TITLE
TEST-#0000: pin `ipython<8.13.0` for python 3.8

### PR DESCRIPTION
**Pull request by anmyachev**
## What do these changes do?

- [x] first commit message and PR title follow format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
  > **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your last commit for the CI job that checks the PR title to pick up the new PR title.
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #? 
- [ ] tests added and passing
- [ ] module layout described at `docs/development/architecture.rst` is up-to-date

### CODE REVIEW

**Comment by dchigarev** [comment]
It seems that `ipython` is being implicitly installed for documentation build, let's try adding the `ipython<8.13.0` restriction in our [requirements-doc.txt file](https://github.com/modin-project/modin/blob/master/docs/requirements-doc.txt)

**Comment by anmyachev** [comment]
Maybe it makes sense to wait for a fix for https://github.com/ipython/ipython/issues/14053

**Comment by dchigarev** [comment]
I think we can wait until Monday and if it won't be fixed until then I'll merge this PR

**Comment by dchigarev** [comment]
so the problem was fixed on ipython's side (https://github.com/ipython/ipython/issues/14053), so closing our issue

**Pull request closed without merging**
