### PR TITLE
FIX-#2326: move s3fs import in _read function

### LINKED ISSUE #2326: Move import s3fs in parquet_reader.py in function scope
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin version** (`modin.__version__`):
- **Python version**:
- **Code we can use to reproduce**:

### Describe the problem

`s3fs` - optional dependence, so we shouldn't import in global scope.

### PR DESCRIPTION
**Pull request by anmyachev**
Signed-off-by: Anatoly Myachev <anatoly.myachev@intel.com>

## What do these changes do?

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/developer/contributing.html)
- [ ] passes `flake8 modin`
- [ ] passes `black --check modin`
- [ ] signed commit with `git commit -s` 
- [x] Resolves #2326 
- [ ] tests added and passing

### CODE REVIEW

**Comment by prutskov** [comment]
@anmyachev Does it make sense to move `import s3fs` in `modin/engines/base/io/file_reader.py` to global scope of this file (this is used in two places in file).

**Comment by anmyachev** [comment]
> @anmyachev Does it make sense to move `import s3fs` in `modin/engines/base/io/file_reader.py` to global scope of this file (this is used in two places in file).

In our case, this shouldn't be done, because we are claiming that `s3fs` is optional. That is, we have to import it only when its functionality is needed (otherwise, the `import modin.pandas` will break for a user who actually does not need this dependency)

**Comment by prutskov** [comment]
@anmyachev ok, LGTM, ping when checks will pass.

**Comment by anmyachev** [comment]
> @anmyachev ok, LGTM, ping me, please, when checks will pass.

ping @prutskov

**Review by prutskov — APPROVED** [review]

**Pull request merged**
