### PR TITLE
FIX-#3915: Add pandas==1.4.0rc0 release candidate to conda env

### LINKED ISSUE #3915: Test pandas pre-release version pandas==1.4.0rc0
We need to test pandas==1.4.0rc0 [pre-release](https://github.com/pandas-dev/pandas/releases/tag/v1.4.0rc0) to potentially report bugs to pandas.

### PR DESCRIPTION
**Pull request by jeffreykennethli**
Signed-off-by: jeffreykennethli <jkli@ponder.io>

## What do these changes do?
Modifies pandas version to the pre-release version pandas==1.4.0rc0 to test compatibility.

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #3915 ? 
- [ ] tests added and passing
- [ ] module layout described at `docs/developer/architecture.rst` is up-to-date

### CODE REVIEW

**Comment by jeffreykennethli** [comment]
The conda install method seems to work better, but there's a conflict with the tests that are configured with python 3.7.

log: `- pandas==1.4.0rc0 -> python[version='>=3.10,<3.11.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0']`

I'm going to try a push with just python 3.8.

**Comment by YarShev** [comment]
I would recommend us waiting for an actual pandas release to test it because I remember when I spent a lot of time in testing a pandas release candidate and searching issues but it happened pandas threw most functionality that I was digging in to get Modin passes CI.

**Comment by YarShev** [comment]
pandas 1.4.0 is available on conda-forge.

**Comment by devin-petersohn** [comment]
I am going to close this and track a new issue for 1.4.

In the future I think it is worth working with the release candidates just so that we don't have to have a long time between pandas and Modin releases.

**Pull request closed without merging**
