### PR TITLE
FIX-#2881: Move to new private Ray API

### LINKED ISSUE #2881: Ray APIs moved to private subpackage on latest master, breaking compatibility
### Describe the problem

Ray [recently moved](https://github.com/ray-project/ray/pull/14607) some of their internal APIs to an explicit `_private` subpackage. Modin calls one of these functions (`ray.utils.get_system_memory()`), leading to errors on tests that run on Ray's latest master.

### Source code / logs
[Example CI logs with failing tests](https://github.com/ray-project/xgboost_ray/pull/66/checks?check_run_id=2114689375)

```
                if object_store_memory is None:
                    # Round down to the nearest Gigabyte.
                    object_store_memory = int(
>                       0.6 * ray.utils.get_system_memory() // 10 ** 9 * 10 ** 9
                    )
E                   AttributeError: module 'ray' has no attribute 'utils'

/opt/hostedtoolcache/Python/3.6.9/x64/lib/python3.6/site-packages/modin/engines/ray/utils.py:132: AttributeError
```

### PR DESCRIPTION
**Pull request by krfricke**
## What do these changes do?

Ray recently moved utility functions to a private subpackage on latest master. This PR addresses these API changes and makes sure to stay compatible with them. 

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [ ] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #2881
- [ ] tests added and passing

### CODE REVIEW

**Review by devin-petersohn — COMMENTED** [review]
Thanks @krfricke! Is there an open issue for this?

The commitlint failure means the first line of your commit message needs to tag the issue. Something like:

```
FIX-#<ISSUE_NUM>: Move to new private Ray API
```

Let me know if this doesn't make sense. Thanks again!

**Comment by krfricke** [comment]
There's no open issue for this, I noticed the failure on our latest master CI and decided to just write a quick patch. I can open an issue if this is required )or move to `REFACTOR` instead?) Let me know what you prefer.

**Comment by devin-petersohn** [comment]
@krfricke Thanks for clarifying, is there a test run for Modin on the Ray CI?

Opening an issue would be best, ideally each PR has an associated issue.

**Comment by krfricke** [comment]
The test is not on the upstream Ray CI, but we're integrating with Modin in `https://github.com/ray-project/xgboost_ray` and run tests for data sources there.

I opened an issue for this fix, can you re-trigger the commit check?

**Comment by devin-petersohn** [comment]
@krfricke Thanks for opening the issue! The commit lint checks check the actual commit message for be98b38, not the PR name. To resolve it you need to rebase and reword be98b38, then force push to your `ray-api` branch. We have found that `git commit --amend` does not work, but rebasing does.

**Comment by krfricke** [comment]
The `codecov/project` check fails though I can't see how this would be related to this PR.

**Comment by devin-petersohn** [comment]
@krfricke Failing codecov is ok in this case. The difference is that we are not yet testing on Ray nightly wheels, so the clause for handling the new API is not yet tested by CI.

Codecov reports are also a bit flaky lately, we are planning to go in and fix it soon.

**Review by devin-petersohn — APPROVED** [review]

**Pull request merged**
