### PR TITLE
DOCS-#2914: add docstrings to data_management/functions component

### LINKED ISSUE #2914: add documentation to data_management/functions component

### PR DESCRIPTION
**Pull request by anmyachev**
Signed-off-by: Anatoly Myachev <anatoly.myachev@intel.com>

## What do these changes do?

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [ ] passes `flake8 modin`
- [ ] passes `black --check modin`
- [ ] signed commit with `git commit -s` 
- [x] Resolves #2914 
- [ ] tests added and passing

### CODE REVIEW

**Comment by anmyachev** [comment]
While writing the documentation for various functions, I came across the fact that `call` method can be deleted without changing the logic.  @devin-petersohn do you have anything against deleting it? (in the future, if necessary, I will divide into two pull requests with refactoring and documentation)

**Comment by devin-petersohn** [comment]
@anmyachev Ideally, call would be used in places where `register` is followed by some parenthesis: https://github.com/modin-project/modin/blob/07c2f86c890f31532ee49bf091cef4e8b036b0bd/modin/backends/pandas/query_compiler.py#L765-L767

I would prefer it be used in those places rather than deleted altogether.

**Comment by anmyachev** [comment]
> @anmyachev Ideally, call would be used in places where `register` is followed by some parenthesis:
> 
> https://github.com/modin-project/modin/blob/07c2f86c890f31532ee49bf091cef4e8b036b0bd/modin/backends/pandas/query_compiler.py#L765-L767
> 
> I would prefer it be used in those places rather than deleted altogether.

If we are talking about the problem of code readability, then I see two options:
1. Just rewrite the calling code a little
```python
max = MapReduceFunction.register(map_func, reduce_func)
return max(self, axis=axis, **kwargs)
```
2. Make `register` return a functor, with implemented method `call`, which will call `__call__` inside itself.
```python
return MapReduceFunction.register(map_func, reduce_func).call(
    self, axis=axis, **kwargs
)
```
It seems to me that the slight improvement in readability is not worth the effort that should be made in the second case.

Can we choose the first option?

**Comment by anmyachev** [comment]
Closed in favor of #2956.

**Pull request closed without merging**
