### PR TITLE
Add "options" support #291

### PR DESCRIPTION
**Pull request by ipacheco-uy**
## What do these changes do?

Add support for options , @devin-petersohn not sure what kind of test to do for this, i test it by checking pd.options.display.max_rows when printing but i don't think its the best option.

## Related issue number

#291 

- [X] passes `flake8 modin`
- [X] passes `black --check modin`
- [X] test added

### CODE REVIEW

**Comment by devin-petersohn** [comment]
Thanks @ipacheco-uy, I think the challenge here is making sure that the updates to the `display` are propagated. Here is internally where `repr` needs to be updated: https://github.com/modin-project/modin/blob/master/modin/pandas/dataframe.py#L134-L136

There are several options in pandas that will be difficult because all of the workers need those options. For now this could work with the `display` options, as long as we change the code in `__repr__`.

For now, the best way to test for the `display` options is probably to just call `repr(some_df)` and make sure that the number of rows/columns is correct. Other than that, as long as the call to pandas `repr` ([link](https://github.com/modin-project/modin/blob/master/modin/pandas/dataframe.py#L138)) gets the correct display options it still should be working.

**Comment by ipacheco-uy** [comment]
Yo are right devin i forgot of the fixed value in dataframe.

**Comment by devin-petersohn** [comment]
Thanks @ipacheco-uy, for some reason the Ray engine was failing due to the `options` being kept around for Modin but not for pandas. I fixed the issue by moving the test below `test___repr__`, which should (hopefully) fix the issue.

**Comment by devin-petersohn** [comment]
The current test failure is fixed by #539, the tests are timing out on Travis.

**Comment by devin-petersohn** [comment]
@ipacheco-uy I went ahead and merged your PR into master. The tests should all be fine now. Thanks again for the PR!

**Pull request merged**
