### PR TITLE
FIX-#6396: set `__factory` to `None` in case of any problems during initialization

### LINKED ISSUE #6396: We should set  `__factory` to `None` in case of any problems that may arise during initialization.
In order not to hide the original error.

### PR DESCRIPTION
**Pull request by anmyachev**
## What do these changes do?

- [x] first commit message and PR title follow format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
  > **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your last commit for the CI job that checks the PR title to pick up the new PR title.
- [x] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] signed commit with `git commit -s` 
- [x] Resolves #6396 
- [x] tests added and passing
- [x] module layout described at `docs/development/architecture.rst` is up-to-date

### CODE REVIEW

**Review by vnlitvinov — COMMENTED** [review]
Could you please elaborate on what exact use case are you improving here?

**Comment by anmyachev** [comment]
> Could you please elaborate on what exact use case are you improving here?

`get_factory` initializes the `__factory` if it has not been initialized before.

https://github.com/modin-project/modin/blob/457c926aa41708a89c882e889896b748578cddf8/modin/core/execution/dispatching/factories/dispatcher.py#L110-L118

[_update_factory](https://github.com/modin-project/modin/blob/457c926aa41708a89c882e889896b748578cddf8/modin/core/execution/dispatching/factories/dispatcher.py#L122C9-L122C24) assigns a factory to `cls.__factory` in any case even if `factory.prepare()` raise an Exception. As a result, all subsequent calls will fall to a partially initialized factory, which can generate non-obvious errors.

**Review by vnlitvinov — APPROVED** [review]
LGTM

**Review by YarShev — APPROVED** [review]

**Comment by anmyachev** [comment]
Thanks @vnlitvinov @YarShev!

**Pull request merged**
