### PR TITLE
FIX-#3114: Fix links to the entities after refactor

### LINKED ISSUE #3114: Documentation broken links
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Any
- **Modin version**: 64d6cb064feac23ed5bfa0cba221f35c512c114e
- **Python version**: Any
- **Code we can use to reproduce**:

### Describe the problem

Commit 64d6cb064feac23ed5bfa0cba221f35c512c114e doesn't take into account the most recent changes from https://github.com/modin-project/modin/pull/3030. For example `docs\flow\modin\engines\ray\pandas_on_ray\frame\partition_manager.rst` denotes `PandasOnRayFrameManager` class, while source code class name is `PandasOnRayFramePartitionManager`.

### PR DESCRIPTION
**Pull request by YarShev**
Signed-off-by: Igoshev, Yaroslav <yaroslav.igoshev@intel.com>

## What do these changes do?

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #3114 
- [x] tests added and passing
- [x] module layout described at `docs/developer/architecture.rst` is up-to-date

### CODE REVIEW

**Review by vnlitvinov — DISMISSED** [review]
LGTM

**Comment by amyskov** [comment]
Let's remove [this line](https://github.com/modin-project/modin/blame/master/docs/developer/architecture.rst#L305) as well.

**Comment by YarShev** [comment]
@amyskov , I believe that should as part of #3099 .

**Review by prutskov — COMMENTED** [review]
Link in these lines isn't working.
1. [line1](https://github.com/YarShev/modin/blame/dev/yigoshev-issue3114/docs/flow/modin/engines/ray/pandas_on_ray/frame/partition.rst#L4) 
2. [line2](https://github.com/YarShev/modin/blame/dev/yigoshev-issue3114/docs/flow/modin/engines/ray/cudf_on_ray/frame/partition.rst#L4)

**Comment by YarShev** [comment]
@prutskov , fixed

**Comment by amyskov** [comment]
> @amyskov , I believe that should as part of #3099 .

But why? It looks like just a typo, it shouldn't generate any warnings.

**Review by prutskov — APPROVED** [review]
LGTM

**Comment by YarShev** [comment]
@amyskov , that is not related to the problem in any way that you described in the issue.

**Comment by amyskov** [comment]
> @amyskov , that is not related to the problem in any way that you described in the issue.

Ok, let's leave it for the issue with warnings.

**Review by amyskov — APPROVED** [review]
LGTM.

**Review by devin-petersohn — APPROVED** [review]
Thanks @YarShev, LGTM!

**Pull request merged**
