### PR TITLE
Update architecture link in modin_vs_dask.md

### PR DESCRIPTION
**Pull request by mGalarnyk**
The link was broken.

## What do these changes do?

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [ ] passes `flake8 modin`
- [ ] passes `black --check modin`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #? 
- [ ] tests added and passing

### CODE REVIEW

**Review by RehanSD — APPROVED** [review]
Thank you so much for adding this! The changes look good to me!

**Comment by devin-petersohn** [comment]
@mGalarnyk Do you mind if I fix the failing test for you? We have requirements on the commit message and I can add the required information pretty quickly for you.

**Comment by mGalarnyk** [comment]
@devin-petersohn Sure! That would be great! Sorry about that! Should have read the guidelines

**Comment by devin-petersohn** [comment]
Whoops, I can't sign off the commit for you.

Can you run `git commit -amend -s` on the branch? You will have to force push after, but that will include the signoff. After that, I can take it from there.

**Comment by mGalarnyk** [comment]
Tried to do the git commit --amend --signoff. Hope it worked. Never contributed to open source before.

**Comment by devin-petersohn** [comment]
@mGalarnyk It worked! #2823 was merged. Thanks again

**Pull request closed without merging**
