### PR TITLE
FIX-#4136: Fix `exercise_3.ipynb` example notebook

### LINKED ISSUE #4136: Example notebook `exercise_3` is broken
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Modin version** (`modin.__version__`): 32cff0d820f0149189d434cc5880f6fa91f5fd70
- **Python version**: 3.8.10
- **Code we can use to reproduce**:

### Describe the problem

`examples\tutorial\tutorial_notebooks\introduction\exercise_3` notebook is broken since pandas 1.4.0 was released, the reason is that `kurtosis` function signature was changed.

### Source code / logs

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_20332/4232529423.py in <module>
      1 custom_start = time.time()
      2 
----> 3 print(df.neg_kurtosis_custom())
      4 
      5 custom_end = time.time()

c:\work\modin\modin\modin\pandas\base.py in __str__(self)
   3125 
   3126     def __str__(self):  # pragma: no cover
-> 3127         return repr(self)
   3128 
   3129     def __xor__(self, other):

c:\work\modin\modin\modin\pandas\series.py in __repr__(self)
    456         num_rows = pandas.get_option("display.max_rows") or 60
    457         num_cols = pandas.get_option("display.max_columns") or 20
--> 458         temp_df = self._build_repr_df(num_rows, num_cols)
    459         if isinstance(temp_df, pandas.DataFrame) and not temp_df.empty:
    460             temp_df = temp_df.iloc[:, 0]

c:\work\modin\modin\modin\pandas\base.py in _build_repr_df(self, num_rows, num_cols)
    200         else:
    201             indexer = row_indexer
--> 202         return self.iloc[indexer]._query_compiler.to_pandas()
    203 
    204     def _update_inplace(self, new_query_compiler):

c:\work\modin\modin\modin\core\storage_formats\pandas\query_compiler.py in to_pandas(self)
    255 
    256     def to_pandas(self):
--> 257         return self._modin_frame.to_pandas()
    258 
    259     @classmethod

c:\work\modin\modin\modin\core\dataframe\pandas\dataframe\dataframe.py in run_f_on_minimally_updated_metadata(self, *args, **kwargs)
    108                 elif apply_axis == "rows":
    109                     obj._propagate_index_objs(axis=0)
--> 110             result = f(self, *args, **kwargs)
    111             if apply_axis is None and not transpose:
    112                 result._deferred_index = self._deferred_index

c:\work\modin\modin\modin\core\dataframe\pandas\dataframe\dataframe.py in to_pandas(self)
   2697         pandas.DataFrame
   2698         """
-> 2699         df = self._partition_mgr_cls.to_pandas(self._partitions)
   2700         if df.empty:
   2701             df = pandas.DataFrame(columns=self.columns, index=self.index)

c:\work\modin\modin\modin\core\dataframe\pandas\partitioning\partition_manager.py in to_pandas(cls, partitions)
    630             A pandas DataFrame
    631         """
--> 632         retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]
    633         if all(
    634             isinstance(part, pandas.Series) for row in retrieved_objects for part in row

c:\work\modin\modin\modin\core\dataframe\pandas\partitioning\partition_manager.py in <listcomp>(.0)
    630             A pandas DataFrame
    631         """
--> 632         retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]
    633         if all(
    634             isinstance(part, pandas.Series) for row in retrieved_objects for part in row

c:\work\modin\modin\modin\core\dataframe\pandas\partitioning\partition_manager.py in <listcomp>(.0)
    630             A pandas DataFrame
    631         """
--> 632         retrieved_objects = [[obj.to_pandas() for obj in part] for part in partitions]
    633         if all(
    634             isinstance(part, pandas.Series) for row in retrieved_objects for part in row

c:\work\modin\modin\modin\core\execution\dask\implementations\pandas_on_dask\partitioning\partition.py in to_pandas(self)
    213         pandas.DataFrame
    214         """
--> 215         dataframe = self.get()
    216         assert type(dataframe) is pandas.DataFrame or type(dataframe) is pandas.Series
    217 

c:\work\modin\modin\modin\core\execution\dask\implementations\pandas_on_dask\partitioning\partition.py in get(self)
     67         if isinstance(self.future, pandas.DataFrame):
     68             return self.future
---> 69         return self.future.result()
     70 
     71     def apply(self, func, *args, **kwargs):

~\.conda\envs\modin\lib\site-packages\distributed\client.py in result(self, timeout)
    236         if self.status == "error":
    237             typ, exc, tb = result
--> 238             raise exc.with_traceback(tb)
    239         elif self.status == "cancelled":
    240             raise result

c:\work\modin\modin\modin\core\execution\dask\implementations\pandas_on_dask\partitioning\virtual_partition.py in deploy_dask_func()
    231         The result of the function ``func`` and metadata for it.
    232     """
--> 233     result = func(*args)
    234     ip = get_ip()
    235     if isinstance(result, pandas.DataFrame):

c:\work\modin\modin\modin\core\dataframe\pandas\partitioning\axis_partition.py in deploy_axis_func()
    158 
    159         dataframe = pandas.concat(list(partitions), axis=axis, copy=False)
--> 160         result = func(dataframe, **kwargs)
    161 
    162         if manual_partition:

c:\work\modin\modin\modin\core\dataframe\pandas\dataframe\dataframe.py in _tree_reduce_func()
   1310         def _tree_reduce_func(df, *args, **kwargs):
   1311             """Tree-reducer function itself executing `func`, presenting the resulting pandas.Series as pandas.DataFrame."""
-> 1312             series_result = func(df, *args, **kwargs)
   1313             if axis == 0 and isinstance(series_result, pandas.Series):
   1314                 # In the case of axis=0, we need to keep the shape of the data

c:\work\modin\modin\modin\core\dataframe\algebra\tree_reduce.py in <lambda>()
     48                     cls.validate_axis(_axis),
     49                     lambda x: map_function(x, *args, **kwargs),
---> 50                     lambda y: reduce_function(y, *args, **kwargs),
     51                 )
     52             )

~\.conda\envs\modin\lib\site-packages\pandas\core\generic.py in kurt()
  11172             **kwargs,
  11173         ):
> 11174             return NDFrame.kurt(self, axis, skipna, level, numeric_only, **kwargs)
  11175 
  11176         setattr(cls, "kurt", kurt)

~\.conda\envs\modin\lib\site-packages\pandas\core\generic.py in kurt()
  10731         **kwargs,
  10732     ) -> Series | float:
> 10733         return self._stat_function(
  10734             "kurt", nanops.nankurt, axis, skipna, level, numeric_only, **kwargs
  10735         )

~\.conda\envs\modin\lib\site-packages\pandas\core\generic.py in _stat_function()
  10618             nv.validate_stat_func((), kwargs, fname=name)
  10619 
> 10620         validate_bool_kwarg(skipna, "skipna", none_allowed=False)
  10621 
  10622         if axis is None and level is None and self.ndim > 1:

~\.conda\envs\modin\lib\site-packages\pandas\util\_validators.py in validate_bool_kwarg()
    249 
    250     if not good_value:
--> 251         raise ValueError(
    252             f'For argument "{arg_name}" expected type bool, received '
    253             f"type {type(value).__name__}."

ValueError: For argument "skipna" expected type bool, received type NoneType.
```

### PR DESCRIPTION
**Pull request by amyskov**
Signed-off-by: Alexander Myskov <alexander.myskov@intel.com>

## What do these changes do?

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
- [x] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] signed commit with `git commit -s` 
- [x] Resolves #4136  
- [ ] tests added and passing
- [x] module layout described at `docs/development/architecture.rst` is up-to-date 
- [ ] added (Issue Number: PR title (PR Number)) and github username to release notes for next major release

### CODE REVIEW

**Comment by amyskov** [comment]
Hi @modin-project/modin-core, please take a look at this PR.

**Review by RehanSD — APPROVED** [review]
LGTM!

**Review by RehanSD — CHANGES_REQUESTED** [review]
LGTM, but could you please add release notes?

**Review by RehanSD — APPROVED** [review]
LGTM! Thank you for adding release note!

**Pull request merged**
