### PR TITLE
FIX-#4115: Unpin `pip` in readthedocs deps list

### LINKED ISSUE #4115: Readthedocs build failed
### Describe the problem

Building of documentation is failing now (https://readthedocs.org/projects/modin/builds/15930731/, https://readthedocs.org/projects/modin/builds/15933959/)
```bash
ERROR: Exception:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/modin/envs/4114/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/modin/envs/4114/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/modin/envs/4114/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 389, in run
    to_install = resolver.get_installation_order(requirement_set)
  File "/home/docs/checkouts/readthedocs.org/user_builds/modin/envs/4114/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 188, in get_installation_order
    weights = get_topological_weights(
  File "/home/docs/checkouts/readthedocs.org/user_builds/modin/envs/4114/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 276, in get_topological_weights
    assert len(weights) == expected_node_count
AssertionError
```

### PR DESCRIPTION
**Pull request by prutskov**
Signed-off-by: Alexey Prutskov <alexey.prutskov@intel.com>

## What do these changes do?

PR removes temporary workaround for building our docs.

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
- [ ] ~~passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`~~
- [ ] ~~passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`~~
- [x] signed commit with `git commit -s` 
- [x] Resolves #4115  
- [x] tests ~~added~~ and passing
- [x] module layout described at `docs/development/architecture.rst` is up-to-date 
- [ ] ~~added (Issue Number: PR title (PR Number)) and github username to release notes for next major release~~  () (too minor change to be highlighted in the notes)

### CODE REVIEW

**Review by YarShev — APPROVED** [review]
@prutskov, LGTM, thanks!

**Comment by YarShev** [comment]
Will merge after release notes are corrected.

**Comment by YarShev** [comment]
Even though the changes are little, I wouldn't say those are minor. The changes highlight that we remove a workaround of the previous issue. If changes fix some quirks/typos, then yes we may not update release notes.

**Comment by prutskov** [comment]
> Even though the changes are little, I wouldn't say those are minor. The changes highlight that we remove a workaround of the previous issue. If changes fix some quirks/typos, then yes we may not update release notes.

Until criteria of addition notes related such minor/not minor changes are not documented it's not unclear when need to add notes or not. And everyone contributor can interpret it differently.

**Comment by YarShev** [comment]
@prutskov, yes, this might be a tricky question. Would you be able to add a note on this in [General Rules for commiters](https://modin.readthedocs.io/en/stable/development/contributing.html#general-rules-for-committers) section where we define criterion?

**Review by YarShev — APPROVED** [review]

**Comment by prutskov** [comment]
> @prutskov, yes, this might be a tricky question. Would you be able to add a note on this in [General Rules for commiters](https://modin.readthedocs.io/en/stable/development/contributing.html#general-rules-for-committers) section where we define criterion?

I'll add

**Pull request merged**
