### PR TITLE
REFACTOR-#5571: Compute length/width cache in apply/drain_call_queue methods of Dask partitions

### LINKED ISSUE #5571: Compute length/width cache in apply/drain_call_queue methods of Dask partitions
This has already been done for partitions on Ray (and Unidist). I see no reason not to do the same for Dask.

### PR DESCRIPTION
**Pull request by anmyachev**
Signed-off-by: Anatoly Myachev <anatoly.myachev@intel.com>

## What do these changes do?

- [x] first commit message and PR title follow format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
  > **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your last commit for the CI job that checks the PR title to pick up the new PR title.
- [x] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] signed commit with `git commit -s` 
- [x] Resolves #5571 
- [x] tests added and passing
- [x] module layout described at `docs/development/architecture.rst` is up-to-date

### CODE REVIEW

**Comment by anmyachev** [comment]
@YarShev could you take a look?

**Review by dchigarev — COMMENTED** [review]
I wonder why it wasn't done before...

Weren't there performance drawbacks when returning multiple values from a dask remote? @Yarshev don't you remember anything related?

**Comment by anmyachev** [comment]
> I wonder why it wasn't done before...
> 
> Weren't there performance drawbacks when returning multiple values from a dask remote? @YarShev don't you remember anything related?

Length caching was added in https://github.com/modin-project/modin/pull/613. At that time, there was already Dask, but another api was used (delayed api). I guess it didn't matter at the time. That's all what I know.

**Comment by YarShev** [comment]
I remember there was performance slowdown when testing such a case (return multiple values from a Dask remote function). That's why I didn't introduce the changes for Dask engine. Most likely, it is because Dask doesn't support multiple values return from its remote functions so we have to use additional remote calls to get the required number of the objects. I highly recommend measuring the performance before we decide if the changes are valuable.

**Comment by anmyachev** [comment]
> I remember there was performance slowdown when testing such a case (return multiple values from a Dask remote function). That's why I didn't introduce the changes for Dask engine. Most likely, it is because Dask doesn't support multiple values return from its remote functions so we have to use additional remote calls to get the required number of the objects. I highly recommend measuring the performance before we decide if the changes are valuable.

Got it. Do you have any benchmarks left?

**Comment by YarShev** [comment]
Unfortunately, no. That was approximately a year ago or even later but, probably, I was just checking the operations that involve block partitions mapping because the changes affect it (map, tree_reduce, broadcast_apply, etc.).

**Pull request closed without merging**
