### PR TITLE
FIX-#3173: fix `push-to-master` test

### LINKED ISSUE #3173: `push-to-master.yml` test fails
### System information
- **Modin version**: f9c99c3817d35f7bf0d91df9aa9644545ea27517
- **Code we can use to reproduce**:
```
docker run --rm --env ray_docker_image:nightly bash -c "pytest modin/experimental/pandas/test/test_io_exp.py"
```

### Describe the problem

`modin/experimental/pandas/test/test_io_exp.py` tests fail in the ray docker container started by `push-to-master.yml` config in the Github Actions. The problem is that resulted `ray_docker_image:nightly` docker image, that is used for tests execution, contains downgraded `sqlalchemy` 1.3.20 version, that is not acceptable for `test_io_exp.py` test.

### Source code / logs

```
modin/experimental/pandas/test/test_io_exp.py:39:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
modin/experimental/pandas/io_exp.py:99: in read_sql
    return DataFrame(query_compiler=FactoryDispatcher.read_sql(**kwargs))
modin/data_management/factories/dispatcher.py:232: in read_sql
    return cls.__factory._read_sql(**kwargs)
modin/data_management/factories/factories.py:471: in _read_sql
    return cls.io_cls.read_sql(**kwargs)
modin/experimental/engines/pandas_on_ray/io_exp.py:176: in read_sql
    cols_names, query = get_query_info(sql, con, partition_column)
modin/experimental/engines/pandas_on_ray/sql.py:224: in get_query_info
    if is_table(engine, sql):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

engine = Engine(sqlite:///test_from_sql_distributed.db)
sql = 'select * from test_from_sql_distributed'

    def is_table(engine, sql):
        """
        Check if given `sql` parameter is a table name.

        Parameters
        ----------
        engine : sqlalchemy.engine.base.Engine
            SQLAlchemy connection engine.
        sql : str
            SQL query to be executed or a table name.

        Returns
        -------
        bool
            Whether `sql` a table name or not.
        """
>       if inspect(engine).has_table(sql):
E       AttributeError: 'Inspector' object has no attribute 'has_table'
```

### PR DESCRIPTION
**Pull request by amyskov**
Signed-off-by: Alexander Myskov <alexander.myskov@intel.com>

## What do these changes do?

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #3173  
- [x] tests added and passing
- [x] module layout described at `docs/developer/architecture.rst` is up-to-date

### CODE REVIEW

**Review by devin-petersohn — COMMENTED** [review]
@amyskov does this need to be a draft anymore?

**Comment by amyskov** [comment]
> @amyskov does this need to be a draft anymore?

@devin-petersohn  i think it should be draft until we change `on` statement in the `push-to-master.yml`. Can we accept proposed changes?

**Review by devin-petersohn — COMMENTED** [review]
@amyskov LGTM, can change from draft now that tests are passing.

**Comment by amyskov** [comment]
@devin-petersohn CI is green now.

**Review by vnlitvinov — APPROVED** [review]
LGTM

**Review by devin-petersohn — APPROVED** [review]
LGTM, thanks @amyskov

**Pull request merged**
