### PR TITLE
TEST-#5154: add `py` to requirements to fix CI failures

### LINKED ISSUE #5154: CI: pytest 7.2.0 dropping `py` from dependencies is causing test failures
See: https://github.com/ionelmc/pytest-benchmark/issues/226 for more context

This is causing failures on master: https://github.com/modin-project/modin/actions/runs/3322482406/jobs/5491562285

### PR DESCRIPTION
**Pull request by pyrito**
## What do these changes do?

- [x] first commit message and PR title follow format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
  > **_NOTE:_**  If you edit the PR title to match this format, you need to add another commit (even if it's empty) or amend your last commit for the CI job that checks the PR title to pick up the new PR title.
- [x] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] signed commit with `git commit -s` 
- [x] Resolves #5154 
- [x] tests added and passing
- [x] module layout described at `docs/development/architecture.rst` is up-to-date

### CODE REVIEW

**Review by mvashishtha — APPROVED** [review]
@pyrito thanks for the fix.

**Comment by pyrito** [comment]
I don't think we need this PR anymore since pytest-benchmark has now been bumped up: https://github.com/ionelmc/pytest-benchmark/issues/226#issuecomment-1291158690.

@mvashishtha could you re-run a workflow to confirm? I'll close the PR then.

**Comment by mvashishtha** [comment]
@pyrito I'm rerunning https://github.com/modin-project/modin/actions/runs/3322482407

**Comment by pyrito** [comment]
Closed since pytest-benchmark has been updated to resolve the issue.

**Pull request closed without merging**
