### PR TITLE
FIX-#4381: Make use Ray back from conda-forge in CI

### LINKED ISSUE #4381: Make use Ray back from conda-forge in CI
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Modin version** (`modin.__version__`):
- **Python version**:
- **Code we can use to reproduce**:

### Describe the problem

Reverting #4364, hopefully new Ray works ok now

### PR DESCRIPTION
**Pull request by Garra1980**
This reverts commit f41432c1c746c6a6186c376594c6c7f7dd24cdb5.

Signed-off-by: izamyati <igor.zamyatin@intel.com>

## What do these changes do?

Reverting #4364 

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [x] signed commit with `git commit -s` 
- [ ] Resolves #4381 
- [ ] tests added and passing
- [ ] module layout described at `docs/development/architecture.rst` is up-to-date 
- [ ] added (Issue Number: PR title (PR Number)) and github username to release notes for next major release

### CODE REVIEW

**Review by devin-petersohn — COMMENTED** [review]
I left a comment in the related issue, I prefer testing with pip

**Comment by Garra1980** [comment]
> I left a comment in the related issue, I prefer testing with pip

Sure, I was wondering whether windows test work with ray from conda

**Comment by RehanSD** [comment]
> > I left a comment in the related issue, I prefer testing with pip
> 
> Sure, I was wondering whether windows test work with ray from conda

Do we plan to merge this PR then?

**Comment by YarShev** [comment]
@RehanSD, take a look at #4381 please. We should reach an agreement there first.

**Comment by anmyachev** [comment]
Ray already used from conda-forge in CI.

**Pull request closed without merging**
