### PR TITLE
Release version 0.16.1

### PR DESCRIPTION
**Pull request by RehanSD**
Signed-off-by: Rehan Durrani <rehan@ponder.io>

## What do these changes do?

- [ ] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/development/contributing.html#commit-message-formatting)
- [ ] passes `flake8 modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] passes `black --check modin/ asv_bench/benchmarks scripts/doc_checker.py`
- [ ] signed commit with `git commit -s` 
- [ ] Resolves #? 
- [ ] tests added and passing
- [ ] module layout described at `docs/development/architecture.rst` is up-to-date

### CODE REVIEW

**Review by mvashishtha — APPROVED** [review]
LGTM, thanks @RehanSD !

**Review by YarShev — CHANGES_REQUESTED** [review]
We should update the links to docs and PyPI in the readme.

See an example here - https://github.com/modin-project/modin/pull/4933

**Comment by mvashishtha** [comment]
@YarShev I don't see links with versions like the ones you updated [here](https://github.com/modin-project/modin/pull/4933/files) in the [README.md](https://github.com/modin-project/modin/blob/abcf1e999d5de710b3e6950c86d026d2cd368351/README.md) source any more

**Comment by YarShev** [comment]
@mvashishtha , that is what I mean

**Comment by mvashishtha** [comment]
@YarShev could you please show exactly what we should change? The readthedocs link and the "pypi package" badges are pointing to the latest versions even though the README code doesn't explicitly state a version.

**Comment by mvashishtha** [comment]
@YarShev I agree we should pin the readthedocs to the latest released version. @RehanSD could you please do that?

Why do we also have to pin the pypi version for the badge? What is wrong with the current URL, which always points to the latest pypi version?

**Comment by mvashishtha** [comment]
@YarShev I agree, so @RehanSD could you please make the changes from @YarShev's [suggestion](https://github.com/modin-project/modin/pull/5116#issuecomment-1274777159)?

**Comment by RehanSD** [comment]
Hi folks! Great catch - I've gone ahead and pinned the docs as well as the PyPi badge!

**Pull request merged**
