### PR TITLE
FIX-#3025: use pandas.DataFrame as return value

### LINKED ISSUE #3025: AttributeError: 'int' object has no attribute 'columns'
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: `Ubuntu 20.04`
- **Modin version** (`modin.__version__`): 8fe4be960440e2bac952491685c9e86c64715b78
- **Python version**: `Python 3.8.6`
- **Code we can use to reproduce**:

```python
import modin.pandas as pd
import ray
ray.init()
import numpy as np
data = np.random.randint(0,100,(2**8,2**8))
df = pd.DataFrame(data)
df.to_csv('/tmp/test.csv')
```

### Describe the problem

https://github.com/modin-project/modin/issues/3014#issuecomment-827740232

### Source code / logs

```bash
2021-04-27 21:25:09,427	INFO services.py:1171 -- View the Ray dashboard at http://127.0.0.1:8265
UserWarning: Distributing <class 'numpy.ndarray'> object. This may take some time.
2021-04-27 21:25:14,874	ERROR worker.py:980 -- Possible unhandled error from worker: ray::deploy_ray_func() (pid=4823, ip=192.168.31.208)
  File "python/ray/_raylet.pyx", line 463, in ray._raylet.execute_task
  File "/home/pratik/miniconda3/lib/python3.8/site-packages/modin/engines/ray/pandas_on_ray/frame/axis_partition.py", line 114, in deploy_ray_func
    result = func(*args)
  File "/home/pratik/miniconda3/lib/python3.8/site-packages/modin/engines/base/frame/axis_partition.py", line 294, in deploy_axis_func
    if sum(lengths) != len(result.columns):
AttributeError: 'int' object has no attribute 'columns'
```

### PR DESCRIPTION
**Pull request by anmyachev**
Signed-off-by: Anatoly Myachev <anatoly.myachev@intel.com>

## What do these changes do?

- [x] commit message follows format outlined [here](https://modin.readthedocs.io/en/latest/contributing.html)
- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #3025 
- [x] tests passing
- [x] module layout described at `docs/developer/architecture.rst` is up-to-date

### CODE REVIEW

**Comment by anmyachev** [comment]
@devin-petersohn ready for review

**Review by vnlitvinov — COMMENTED** [review]
TBH this change looks very weird, but I see why it helps.

I still think this should be declared a workaround, because current internal API that we use here expects the "partition func" to return the resulting chunk retaining its shape.

cc @YarShev

**Comment by YarShev** [comment]
I am not sure of what the reason to return `0` as synchronization purposes from the apply function but we should probably return pandas DataFrame from it. Moreover, this DataFrame should be `df` that is passed in the function because there might be the error [here](https://github.com/modin-project/modin/blob/master/modin/data_management/utils.py#L103) when iterating over the empty DataFrame.

**Comment by anmyachev** [comment]
> I am not sure of what the reason to return `0` as synchronization purposes from the apply function but we should probably return pandas DataFrame from it. Moreover, this DataFrame should be `df` that is passed in the function because there might be the error [here](https://github.com/modin-project/modin/blob/master/modin/data_management/utils.py#L103) when iterating over the empty DataFrame.

Returning zero is cheaper than a dataframe, due to it still needs to be created.

Returning the same dataframe that was passed in the function is expensive, since it still needs to be written to object storage.

**Comment by YarShev** [comment]
As for performance, we can return something like `pandas.DataFrame([], columns=np.arange(len(df.columns)))`.

**Comment by anmyachev** [comment]
> As for performance, we can return something like `pandas.DataFrame([], columns=np.arange(len(df.columns)))`.

But why? We have tests that don't break when using an empty dataframe.

**Comment by vnlitvinov** [comment]
Because that's the expected behaviour - mapping functions should not change the shape of underlying frames, and here you end up with empty frame.

**Comment by vnlitvinov** [comment]
cc @devin-petersohn 
Maybe we should create a portion of API that would behave just like that (i.e. would allow running some functions over the dataframe, be it block-by-block or axis-wise) that would _not_ expect a `DataFrame` as a result, i.e. effectively create a "scalar" transformation somehow - this is exactly what `to_csv()` does, it transforms our DataFrame into a file and a scalar result (either `None` or a `str` with some details on csv format).

**Comment by devin-petersohn** [comment]
@vnlitvinov Let's create a new issue to track that. The source of the issue here is that we need to block on some return value, and Modin internal APIs expect partitions to be in their specific format. We probably need to have specific utilities for writing the partitions out to some other format.

Since this is blocking existing users, let's do that later.

**Review by devin-petersohn — APPROVED** [review]

**Comment by vnlitvinov** [comment]
> Let's create a new issue to track that.

Created #3036, everyone feel free to edit it if you see fit.

**Pull request merged**
