### PR TITLE
Updated required python version to 3.6.1+

### LINKED ISSUE #1550: Update python version requirements to 3.6.1+
Modin requires pandas 1.0.3, which minimum python version is 3.6.1: [link](https://github.com/pandas-dev/pandas/blob/master/setup.py#L774)

But at Modin [setup.py](https://github.com/modin-project/modin/blob/master/setup.py#L68) required version is 3.5. We should to get rid of that inconsistency by updating it to 3.6.1

### PR DESCRIPTION
**Pull request by dchigarev**
Signed-off-by: Dmitry Chigarev <dmitry.chigarev@intel.com>

## What do these changes do?

- [x] passes `flake8 modin`
- [x] passes `black --check modin`
- [x] signed commit with `git commit -s` 
- [x] Resolves #1550 
- [ ] tests added and passing

### CODE REVIEW

**Comment by devin-petersohn** [comment]
Please also update the pandas version to 1.0.4 https://github.com/pandas-dev/pandas/releases/tag/v1.0.4

**Comment by dchigarev** [comment]
done

**Comment by dchigarev** [comment]
After updating pandas to 1.0.4 parquet tests from `test_io.py` starts failing.
It seems that changes in [this](https://github.com/pandas-dev/pandas/pull/33632) PR caused that problem

**Comment by dchigarev** [comment]
@devin-petersohn parquet fails seems to be fixed, but there is another problem:
at pandas 1.0.4 [s3 reading from public buckets is broken](https://github.com/pandas-dev/pandas/issues/34626) and that's why we get CI red now. Fixing of that bug was added to 1.0.5 milestone, so we could skip the current pandas version and updates only when 1.0.5 will be released, or just mark failing test as `xfail` for now

**Comment by devin-petersohn** [comment]
@dchigarev Let's wait on the upgrade for pandas. Reading from S3 public buckets is an important functionality.

**Comment by dchigarev** [comment]
> @dchigarev Let's wait on the upgrade for pandas. Reading from S3 public buckets is an important functionality.

should we update required python version to 3.6.1+ and stay at pandas 1.0.3?

**Comment by devin-petersohn** [comment]
@dchigarev Yes, I think that is fine for now.

**Comment by dchigarev** [comment]
> @dchigarev Yes, I think that is fine for now.

done

**Pull request merged**
